// Generated by feathers-baas. Safe to edit.
import { mkdirSync, writeFileSync, copyFileSync, existsSync, readdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { execSync } from 'node:child_process'
import { renderTemplate, getTemplatePath } from '../utils/template.js'
import * as output from '../utils/output.js'

export type StorageDriver = 'local' | 's3' | 'gcs' | 'none'
export type EmailDriver = 'none' | 'smtp' | 'resend' | 'sendgrid' | 'brevo'

export interface AppOptions {
  projectName: string
  database: 'postgresql' | 'mysql' | 'sqlite' | 'mongodb'
  projectRoot: string
  storageDriver: StorageDriver
  emailDriver: EmailDriver
}

function copyTemplateDir(templateRelDir: string, destDir: string, projectRoot: string): void {
  const srcDir = getTemplatePath(templateRelDir)
  if (!existsSync(srcDir)) return
  for (const name of readdirSync(srcDir)) {
    const src = join(srcDir, name)
    const dest = join(destDir, name)
    copyFileSync(src, dest)
    output.fileCreated(dest.replace(projectRoot + '/', ''))
  }
}

function getLatestVersion(pkg: string): string {
  try {
    return execSync(`npm view ${pkg} version`, { encoding: 'utf-8' }).trim()
  } catch {
    return '0.1.0'
  }
}

const STATIC_FILES = [
  'tsconfig.json',
  'tsup.config.ts',
  'src/declarations.ts',
  'src/services/index.ts',
  'src/migrate.ts',
  'src/seed.ts',
]

const EJS_FILES = [
  { template: 'app/package.json.ejs', output: 'package.json' },
  { template: 'app/.env.example.ejs', output: '.env.example' },
  { template: 'app/src/index.ts.ejs', output: 'src/index.ts' },
]

const KNEX_EJS_FILES = [
  { template: 'app/knexfile.ts.ejs', output: 'knexfile.ts' },
]

export function generateApp(options: AppOptions): void {
  const { projectName, database, projectRoot, storageDriver, emailDriver } = options

  if (existsSync(projectRoot)) {
    throw new Error(`Directory "${projectRoot}" already exists. Use a different name or remove it first.`)
  }

  mkdirSync(projectRoot, { recursive: true })

  output.info('Fetching latest package versions...')
  const versions = {
    core: getLatestVersion('@feathers-baas/core'),
    cli: getLatestVersion('feathers-baas'),
    pluginFiles: getLatestVersion('@feathers-baas/plugin-files'),
    pluginNotifications: getLatestVersion('@feathers-baas/plugin-notifications'),
  }

  const templateData = { projectName, database, versions, storageDriver, emailDriver }

  // Copy static files
  for (const file of STATIC_FILES) {
    const src = getTemplatePath(`app/${file}`)
    const dest = join(projectRoot, file)
    mkdirSync(dirname(dest), { recursive: true })
    copyFileSync(src, dest)
    output.fileCreated(file)
  }

  // Copy .gitignore (named .gitignore.template to avoid npm stripping it)
  const gitignoreSrc = getTemplatePath('app/.gitignore.template')
  const gitignoreDest = join(projectRoot, '.gitignore')
  copyFileSync(gitignoreSrc, gitignoreDest)
  output.fileCreated('.gitignore')

  // Copy Docker files
  const dockerFiles = ['Dockerfile', 'docker-compose.yml', '.dockerignore', 'docker-entrypoint.sh']
  for (const file of dockerFiles) {
    const src = getTemplatePath(`docker/${file}`)
    if (existsSync(src)) {
      copyFileSync(src, join(projectRoot, file))
      output.fileCreated(file)
    }
  }

  // Copy AGENTS.md
  const agentsSrc = getTemplatePath('AGENTS.md')
  if (existsSync(agentsSrc)) {
    copyFileSync(agentsSrc, join(projectRoot, 'AGENTS.md'))
    output.fileCreated('AGENTS.md')
  }

  // Render EJS templates
  for (const { template, output: outFile } of EJS_FILES) {
    const content = renderTemplate(template, templateData)
    const dest = join(projectRoot, outFile)
    mkdirSync(dirname(dest), { recursive: true })
    writeFileSync(dest, content, 'utf-8')
    output.fileCreated(outFile)
  }

  // Knex-specific files (SQL databases only)
  if (database !== 'mongodb') {
    for (const { template, output: outFile } of KNEX_EJS_FILES) {
      const content = renderTemplate(template, templateData)
      const dest = join(projectRoot, outFile)
      mkdirSync(dirname(dest), { recursive: true })
      writeFileSync(dest, content, 'utf-8')
      output.fileCreated(outFile)
    }

    // Create migrations directory (seeding is handled by `feathers-baas seed`)
    const migrationsDir = join(projectRoot, 'migrations')
    mkdirSync(migrationsDir, { recursive: true })

    // Ship default core migrations for PostgreSQL.
    // MySQL/SQLite migrations aren't yet provided by core, so leave those empty.
    if (database === 'postgresql') {
      copyTemplateDir('app/migrations', migrationsDir, projectRoot)
    }
  }

  // Create src/hooks directory and copy built-in hooks
  const hooksDir = join(projectRoot, 'src', 'hooks')
  mkdirSync(hooksDir, { recursive: true })
  copyTemplateDir('app/src/hooks', hooksDir, projectRoot)

  // Copy .env.example to .env
  const envExample = join(projectRoot, '.env.example')
  const envFile = join(projectRoot, '.env')
  copyFileSync(envExample, envFile)
}

