// Generated by feathers-baas. Safe to edit.
import { mkdirSync, writeFileSync, copyFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { renderTemplate, getTemplatePath } from '../utils/template.js'
import * as output from '../utils/output.js'

export interface AppOptions {
  projectName: string
  database: 'postgresql' | 'mysql' | 'sqlite' | 'mongodb'
  projectRoot: string
}

const STATIC_FILES = [
  'tsconfig.json',
  'tsup.config.ts',
  'src/services/index.ts',
]

const EJS_FILES = [
  { template: 'app/package.json.ejs', output: 'package.json' },
  { template: 'app/.env.example.ejs', output: '.env.example' },
  { template: 'app/src/index.ts.ejs', output: 'src/index.ts' },
]

const KNEX_EJS_FILES = [
  { template: 'app/knexfile.ts.ejs', output: 'knexfile.ts' },
]

export function generateApp(options: AppOptions): void {
  const { projectName, database, projectRoot } = options

  if (existsSync(projectRoot)) {
    throw new Error(`Directory "${projectRoot}" already exists. Use a different name or remove it first.`)
  }

  mkdirSync(projectRoot, { recursive: true })

  const templateData = { projectName, database }

  // Copy static files
  for (const file of STATIC_FILES) {
    const src = getTemplatePath(`app/${file}`)
    const dest = join(projectRoot, file)
    mkdirSync(dirname(dest), { recursive: true })
    copyFileSync(src, dest)
    output.fileCreated(file)
  }

  // Copy .gitignore (named .gitignore.template to avoid npm stripping it)
  const gitignoreSrc = getTemplatePath('app/.gitignore.template')
  const gitignoreDest = join(projectRoot, '.gitignore')
  copyFileSync(gitignoreSrc, gitignoreDest)
  output.fileCreated('.gitignore')

  // Copy Docker files
  const dockerFiles = ['Dockerfile', 'docker-compose.yml', '.dockerignore']
  for (const file of dockerFiles) {
    const src = getTemplatePath(`docker/${file}`)
    if (existsSync(src)) {
      copyFileSync(src, join(projectRoot, file))
      output.fileCreated(file)
    }
  }

  // Copy AGENTS.md
  const agentsSrc = getTemplatePath('AGENTS.md')
  if (existsSync(agentsSrc)) {
    copyFileSync(agentsSrc, join(projectRoot, 'AGENTS.md'))
    output.fileCreated('AGENTS.md')
  }

  // Render EJS templates
  for (const { template, output: outFile } of EJS_FILES) {
    const content = renderTemplate(template, templateData)
    const dest = join(projectRoot, outFile)
    mkdirSync(dirname(dest), { recursive: true })
    writeFileSync(dest, content, 'utf-8')
    output.fileCreated(outFile)
  }

  // Knex-specific files (SQL databases only)
  if (database !== 'mongodb') {
    for (const { template, output: outFile } of KNEX_EJS_FILES) {
      const content = renderTemplate(template, templateData)
      const dest = join(projectRoot, outFile)
      mkdirSync(dirname(dest), { recursive: true })
      writeFileSync(dest, content, 'utf-8')
      output.fileCreated(outFile)
    }

    // Create migrations and seeds directories
    mkdirSync(join(projectRoot, 'migrations'), { recursive: true })
    mkdirSync(join(projectRoot, 'seeds'), { recursive: true })
  }

  // Create src/hooks directory for generate hook
  mkdirSync(join(projectRoot, 'src', 'hooks'), { recursive: true })

  // Copy .env.example to .env
  const envExample = join(projectRoot, '.env.example')
  const envFile = join(projectRoot, '.env')
  copyFileSync(envExample, envFile)
}

