// Generated by feathers-baas. Safe to edit.
import { writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { renderTemplate } from '../utils/template.js'
import { toCamelCase, toKebabCase } from '../utils/naming.js'
import * as output from '../utils/output.js'

export interface HookGeneratorOptions {
  name: string
  projectRoot: string
}

export function generateHook(opts: HookGeneratorOptions): void {
  const { name, projectRoot } = opts
  const kebabName = toKebabCase(name)
  const camelName = toCamelCase(name)

  const hooksDir = join(projectRoot, 'src', 'hooks')
  const filePath = join(hooksDir, `${kebabName}.ts`)

  if (existsSync(filePath)) {
    throw new Error(`Hook file already exists: ${filePath}`)
  }

  const content = renderTemplate('hook/hook.ts.ejs', { camelName })
  writeFileSync(filePath, content, 'utf-8')
  output.fileCreated(filePath.replace(projectRoot + '/', ''))
}
