// Generated by feathers-baas. Safe to edit.
import { writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { Project, SyntaxKind } from 'ts-morph'
import { renderTemplate } from '../utils/template.js'
import { toCamelCase, toPascalCase, toSnakeCase, toKebabCase } from '../utils/naming.js'
import type { Database } from '../utils/detect-database.js'
import * as output from '../utils/output.js'

export interface FieldDefinition {
  name: string
  type: 'string' | 'number' | 'boolean' | 'text' | 'json'
  required: boolean
  queryable: boolean
  typebox: string
  typeboxBase: string
  knexColumn: string
}

export interface ServiceGeneratorOptions {
  name: string
  fields: FieldDefinition[]
  projectRoot: string
  database: Database
}

function typeboxBaseForType(type: string): string {
  const base: Record<string, string> = {
    string: 'Type.String()',
    number: 'Type.Number()',
    boolean: 'Type.Boolean()',
    text: 'Type.String()',
    json: 'Type.Any()',
  }
  return base[type] ?? 'Type.String()'
}

function typeboxForField(field: { name: string; type: string; required: boolean }): string {
  const expr = typeboxBaseForType(field.type)
  return field.required ? expr : `Type.Optional(${expr})`
}

function knexColumnForField(field: { name: string; type: string; required: boolean }): string {
  const snakeName = toSnakeCase(field.name)
  const map: Record<string, string> = {
    string: `table.string('${snakeName}')`,
    number: `table.integer('${snakeName}')`,
    boolean: `table.boolean('${snakeName}')`,
    text: `table.text('${snakeName}')`,
    json: `table.jsonb('${snakeName}')`,
  }
  const col = map[field.type] ?? `table.string('${snakeName}')`
  return field.required ? `${col}.notNullable()` : `${col}.nullable()`
}

export function buildFields(
  raw: Array<{ name: string; type: string; required?: boolean }>,
): FieldDefinition[] {
  return raw.map((f) => ({
    name: toCamelCase(f.name),
    type: f.type as FieldDefinition['type'],
    required: f.required ?? true,
    queryable: ['string', 'number', 'boolean'].includes(f.type),
    typebox: typeboxForField({ ...f, name: toCamelCase(f.name), required: f.required ?? true }),
    typeboxBase: typeboxBaseForType(f.type),
    knexColumn: knexColumnForField({ ...f, name: toCamelCase(f.name), required: f.required ?? true }),
  }))
}

export function generateService(opts: ServiceGeneratorOptions): void {
  const { name, fields, projectRoot, database } = opts
  const kebabName = toKebabCase(name)
  const camelName = toCamelCase(name)
  const pascalName = toPascalCase(name)
  const tableName = toSnakeCase(name)

  const srcDir = join(projectRoot, 'src')
  const serviceDir = join(srcDir, 'services', kebabName)
  const migrationsDir = join(projectRoot, 'migrations')

  if (existsSync(serviceDir)) {
    throw new Error(`Service directory already exists: ${serviceDir}`)
  }

  mkdirSync(serviceDir, { recursive: true })

  const templateData = { kebabName, camelName, pascalName, tableName, fields, database }

  const filesToCreate: Array<{ template: string; filename: string; dir: string }> = [
    { template: 'service/schema.ts.ejs', filename: `${kebabName}.schema.ts`, dir: serviceDir },
    { template: 'service/class.ts.ejs', filename: `${kebabName}.class.ts`, dir: serviceDir },
    { template: 'service/hooks.ts.ejs', filename: `${kebabName}.hooks.ts`, dir: serviceDir },
    { template: 'service/service.ts.ejs', filename: `${kebabName}.service.ts`, dir: serviceDir },
  ]

  for (const f of filesToCreate) {
    const content = renderTemplate(f.template, templateData)
    const filePath = join(f.dir, f.filename)
    writeFileSync(filePath, content, 'utf-8')
    const rel = filePath.replace(projectRoot + '/', '')
    output.fileCreated(rel)
  }

  if (database !== 'mongodb') {
    const migrationNumber = nextMigrationNumber(migrationsDir)
    const migrationFilename = `${migrationNumber}_create_${tableName}.ts`
    const migrationContent = renderTemplate('service/migration.ts.ejs', templateData)
    const migrationPath = join(migrationsDir, migrationFilename)
    writeFileSync(migrationPath, migrationContent, 'utf-8')
    output.fileCreated(migrationPath.replace(projectRoot + '/', ''))
  }

  patchServiceIndex(srcDir, kebabName, pascalName)
  patchDeclarations(srcDir, kebabName, pascalName)
}

function nextMigrationNumber(migrationsDir: string): string {
  if (!existsSync(migrationsDir)) {
    mkdirSync(migrationsDir, { recursive: true })
    return '20240001'
  }
  const files = readdirSync(migrationsDir).sort()
  if (files.length === 0) return '20240001'
  const last = files[files.length - 1]!
  const match = last.match(/^(\d+)/)
  if (!match) return '20240001'
  return String(Number(match[1]) + 1).padStart(8, '0')
}

function patchServiceIndex(srcDir: string, kebabName: string, pascalName: string): void {
  const indexPath = join(srcDir, 'services', 'index.ts')
  const project = new Project({ tsConfigFilePath: undefined })
  const sourceFile = project.addSourceFileAtPath(indexPath)

  const importPath = `./${kebabName}/${kebabName}.service.js`
  const configureFnName = `configure${pascalName}`

  sourceFile.addImportDeclaration({
    moduleSpecifier: importPath,
    namedImports: [configureFnName],
  })

  const configureServices = sourceFile.getFunction('configureServices')
  if (configureServices) {
    const body = configureServices.getBody()
    if (body && body.getKind() === SyntaxKind.Block) {
      const block = body.asKindOrThrow(SyntaxKind.Block)
      block.addStatements(`${configureFnName}(app)`)
    }
  }

  sourceFile.formatText({ indentSize: 2 })
  sourceFile.saveSync()
  output.filePatched('src/services/index.ts')
}

function patchDeclarations(srcDir: string, kebabName: string, pascalName: string): void {
  const declPath = join(srcDir, 'declarations.ts')
  if (!existsSync(declPath)) return

  const project = new Project({ tsConfigFilePath: undefined })
  const sourceFile = project.addSourceFileAtPath(declPath)

  const classImportPath = `./services/${kebabName}/${kebabName}.class.js`
  const className = `${pascalName}Class`

  sourceFile.addImportDeclaration({
    moduleSpecifier: classImportPath,
    namedImports: [className],
    isTypeOnly: true,
  })

  const serviceTypesInterface = sourceFile.getInterface('ServiceTypes')
  if (serviceTypesInterface) {
    serviceTypesInterface.addProperty({
      name: kebabName.includes('-') ? `'${kebabName}'` : kebabName,
      type: className,
    })
  }

  sourceFile.formatText({ indentSize: 2 })
  sourceFile.saveSync()
  output.filePatched('src/declarations.ts')
}
