// Generated by feathers-baas. Safe to edit.
import { Command, Option } from 'clipanion'
import { resolve, join } from 'node:path'
import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs'

interface ServiceInfo {
  name: string
  path: string
  methods: string[]
  files: string[]
}

interface ProjectDescription {
  name: string
  version: string
  services: ServiceInfo[]
  hooks: string[]
  migrations: string[]
  database: string | null
}

function detectDatabase(projectRoot: string): string | null {
  const pkgPath = join(projectRoot, 'package.json')
  if (!existsSync(pkgPath)) return null

  const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8')) as Record<string, unknown>
  const deps = {
    ...(pkg['dependencies'] as Record<string, string> | undefined),
    ...(pkg['devDependencies'] as Record<string, string> | undefined),
  }

  if (deps['pg']) return 'postgresql'
  if (deps['mysql2']) return 'mysql'
  if (deps['better-sqlite3']) return 'sqlite'
  if (deps['mongodb']) return 'mongodb'
  return null
}

function discoverServices(srcDir: string): ServiceInfo[] {
  const servicesDir = join(srcDir, 'services')
  if (!existsSync(servicesDir)) return []

  const services: ServiceInfo[] = []

  for (const entry of readdirSync(servicesDir)) {
    const entryPath = join(servicesDir, entry)
    if (!statSync(entryPath).isDirectory()) continue

    const serviceFile = join(entryPath, `${entry}.service.ts`)
    if (!existsSync(serviceFile)) continue

    const content = readFileSync(serviceFile, 'utf-8')

    const methodsMatch = content.match(/methods:\s*\[([^\]]*)\]/)
    const methods = methodsMatch
      ? methodsMatch[1]!.split(',').map((m) => m.trim().replace(/['"]/g, '')).filter(Boolean)
      : ['find', 'get', 'create', 'patch', 'remove']

    const files = readdirSync(entryPath).filter((f) => f.endsWith('.ts'))

    services.push({
      name: entry,
      path: `/${entry}`,
      methods,
      files: files.map((f) => `src/services/${entry}/${f}`),
    })
  }

  return services
}

function discoverHooks(srcDir: string): string[] {
  const hooksDir = join(srcDir, 'hooks')
  if (!existsSync(hooksDir)) return []

  return readdirSync(hooksDir)
    .filter((f) => f.endsWith('.ts'))
    .map((f) => f.replace('.ts', ''))
}

function discoverMigrations(projectRoot: string): string[] {
  const migrationsDir = join(projectRoot, 'migrations')
  if (!existsSync(migrationsDir)) return []

  return readdirSync(migrationsDir)
    .filter((f) => f.endsWith('.ts'))
    .sort()
}

export class DescribeCommand extends Command {
  static override paths = [['describe']]

  static override usage = Command.Usage({
    description: 'Introspect registered services, methods, and schemas — JSON output for agent consumption',
    examples: [
      ['Describe project', 'feathers-baas describe'],
      ['From specific path', 'feathers-baas describe --path ./my-app'],
    ],
  })

  projectPath = Option.String('--path,-p', { description: 'Project root path', required: false })

  async execute(): Promise<void> {
    const projectRoot = resolve(this.projectPath ?? process.cwd())
    const srcDir = join(projectRoot, 'src')

    const pkgPath = join(projectRoot, 'package.json')
    let name = 'unknown'
    let version = '0.0.0'
    if (existsSync(pkgPath)) {
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8')) as Record<string, unknown>
      name = (pkg['name'] as string) ?? 'unknown'
      version = (pkg['version'] as string) ?? '0.0.0'
    }

    const description: ProjectDescription = {
      name,
      version,
      services: discoverServices(srcDir),
      hooks: discoverHooks(srcDir),
      migrations: discoverMigrations(projectRoot),
      database: detectDatabase(projectRoot),
    }

    console.log(JSON.stringify(description, null, 2))
  }
}
