// Generated by feathers-baas. Safe to edit.
import { Command, Option } from 'clipanion'
import { resolve, join } from 'node:path'
import { readFileSync, existsSync } from 'node:fs'
import * as output from '../utils/output.js'

interface CheckResult {
  name: string
  status: 'pass' | 'warn' | 'fail'
  message: string
}

async function checkEnvVars(projectRoot: string): Promise<CheckResult[]> {
  const results: CheckResult[] = []
  const envPath = join(projectRoot, '.env')

  if (!existsSync(envPath)) {
    results.push({ name: 'env-file', status: 'warn', message: '.env file not found' })
    return results
  }

  results.push({ name: 'env-file', status: 'pass', message: '.env file exists' })

  const envContent = readFileSync(envPath, 'utf-8')
  const envVars = new Map<string, string>()
  for (const line of envContent.split('\n')) {
    const match = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/)
    if (match) envVars.set(match[1]!, match[2]!)
  }

  const hasDb = envVars.has('DATABASE_URL') || envVars.has('MYSQL_URL') ||
    envVars.has('SQLITE_FILENAME') || envVars.has('MONGODB_URL')
  results.push(hasDb
    ? { name: 'database-url', status: 'pass', message: 'Database connection configured' }
    : { name: 'database-url', status: 'fail', message: 'No database env var set (DATABASE_URL, MYSQL_URL, SQLITE_FILENAME, or MONGODB_URL)' })

  const jwtSecret = envVars.get('JWT_SECRET') ?? ''
  if (!jwtSecret) {
    results.push({ name: 'jwt-secret', status: 'fail', message: 'JWT_SECRET not set' })
  } else if (jwtSecret.length < 32) {
    results.push({ name: 'jwt-secret', status: 'warn', message: `JWT_SECRET is ${jwtSecret.length} chars (minimum 32 recommended)` })
  } else {
    results.push({ name: 'jwt-secret', status: 'pass', message: 'JWT_SECRET is set (32+ chars)' })
  }

  return results
}

async function checkDatabase(projectRoot: string): Promise<CheckResult> {
  try {
    const knexfilePath = join(projectRoot, 'knexfile.ts')
    if (!existsSync(knexfilePath)) {
      return { name: 'database-connection', status: 'warn', message: 'knexfile.ts not found — skipping DB check' }
    }

    const { execSync } = await import('node:child_process')
    execSync('node --import tsx/esm -e "const k = require(\'knex\'); process.exit(0)"', {
      cwd: projectRoot,
      timeout: 10_000,
      stdio: 'pipe',
    })
    return { name: 'database-connection', status: 'pass', message: 'Database driver is installed' }
  } catch {
    return { name: 'database-connection', status: 'warn', message: 'Could not verify database driver' }
  }
}

async function checkVersionConsistency(projectRoot: string): Promise<CheckResult> {
  const pkgPath = join(projectRoot, 'package.json')
  if (!existsSync(pkgPath)) {
    return { name: 'version-consistency', status: 'fail', message: 'package.json not found' }
  }

  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8')) as Record<string, unknown>
    const deps = { ...(pkg['dependencies'] as Record<string, string> | undefined) }
    const feathersDeps = Object.entries(deps).filter(([name]) => name.startsWith('@feathersjs/'))

    if (feathersDeps.length === 0) {
      return { name: 'version-consistency', status: 'warn', message: 'No @feathersjs/* dependencies found' }
    }

    const versions = new Set(feathersDeps.map(([, v]) => v))
    if (versions.size === 1) {
      return { name: 'version-consistency', status: 'pass', message: `All @feathersjs/* packages at ${[...versions][0]}` }
    }

    const details = feathersDeps.map(([n, v]) => `${n}@${v}`).join(', ')
    return { name: 'version-consistency', status: 'warn', message: `Mixed @feathersjs/* versions: ${details}` }
  } catch {
    return { name: 'version-consistency', status: 'fail', message: 'Could not parse package.json' }
  }
}

async function checkMigrations(projectRoot: string): Promise<CheckResult> {
  const migrationsDir = join(projectRoot, 'migrations')
  if (!existsSync(migrationsDir)) {
    return { name: 'migrations', status: 'warn', message: 'No migrations/ directory found' }
  }
  return { name: 'migrations', status: 'pass', message: 'Migrations directory exists' }
}

export class DoctorCommand extends Command {
  static override paths = [['doctor']]

  static override usage = Command.Usage({
    description: 'Check project health: env vars, DB, versions, migrations',
    examples: [
      ['Run doctor', 'feathers-baas doctor'],
      ['JSON output', 'feathers-baas doctor --json'],
    ],
  })

  projectPath = Option.String('--path,-p', { description: 'Project root path', required: false })
  json = Option.Boolean('--json', false, { description: 'Output results as JSON' })

  async execute(): Promise<void> {
    const projectRoot = resolve(this.projectPath ?? process.cwd())
    const results: CheckResult[] = []

    results.push(...await checkEnvVars(projectRoot))
    results.push(await checkDatabase(projectRoot))
    results.push(await checkVersionConsistency(projectRoot))
    results.push(await checkMigrations(projectRoot))

    if (this.json) {
      const hasFailure = results.some((r) => r.status === 'fail')
      console.log(JSON.stringify({ success: !hasFailure, checks: results }, null, 2))
      if (hasFailure) process.exitCode = 1
      return
    }

    output.info(`Checking project at ${projectRoot}\n`)

    let hasFailure = false
    for (const check of results) {
      if (check.status === 'pass') {
        output.success(`${check.name}: ${check.message}`)
      } else if (check.status === 'warn') {
        output.warn(`${check.name}: ${check.message}`)
      } else {
        output.error(`${check.name}: ${check.message}`)
        hasFailure = true
      }
    }

    console.log()
    if (hasFailure) {
      output.error('Some checks failed — fix the issues above before continuing.')
      process.exitCode = 1
    } else {
      output.success('All checks passed!')
    }
  }
}
