// Generated by feathers-baas. Safe to edit.
import { Command, Option } from 'clipanion'
import { input, confirm } from '@inquirer/prompts'
import { resolve } from 'node:path'
import { generateService, buildFields } from '../generators/service.generator.js'
import * as output from '../utils/output.js'

interface RawField {
  name: string
  type: string
  required?: boolean
}

async function promptFields(): Promise<RawField[]> {
  const fields: RawField[] = []
  let addMore = true

  while (addMore) {
    const name = await input({ message: 'Field name:' })
    const type = await input({
      message: `Field type for "${name}" (string, number, boolean, text, json):`,
      default: 'string',
      validate: (v) =>
        ['string', 'number', 'boolean', 'text', 'json'].includes(v) || 'Must be one of: string, number, boolean, text, json',
    })
    const required = await confirm({ message: `Is "${name}" required?`, default: true })
    fields.push({ name, type, required })
    addMore = await confirm({ message: 'Add another field?', default: true })
  }

  return fields
}

function parseFieldsFlag(raw: string): RawField[] {
  return raw.split(',').map((entry) => {
    const parts = entry.trim().split(':')
    const name = parts[0]!
    const type = parts[1] ?? 'string'
    const required = parts[2] !== 'optional'
    return { name, type, required }
  })
}

export class GenerateServiceCommand extends Command {
  static override paths = [['generate', 'service']]

  static override usage = Command.Usage({
    description: 'Generate a new Feathers service (schema, class, hooks, service, migration)',
    examples: [
      ['Interactive mode', 'feathers-baas generate service'],
      ['With name', 'feathers-baas generate service --name posts'],
      ['With fields', 'feathers-baas generate service --name posts --fields title:string,body:text,published:boolean'],
    ],
  })

  name = Option.String('--name,-n', { description: 'Service name (kebab-case)', required: false })
  fields = Option.String('--fields,-f', { description: 'Comma-separated fields (name:type[:optional])', required: false })
  projectPath = Option.String('--path,-p', { description: 'Project root path', required: false })

  async execute(): Promise<void> {
    try {
      const projectRoot = resolve(this.projectPath ?? process.cwd())

      const serviceName = this.name ?? await input({
        message: 'Service name (kebab-case, e.g. "blog-posts"):',
        validate: (v) => /^[a-z][a-z0-9-]*$/.test(v) || 'Must be lowercase with hyphens only',
      })

      let rawFields: RawField[]
      if (this.fields) {
        rawFields = parseFieldsFlag(this.fields)
      } else {
        rawFields = await promptFields()
      }

      if (rawFields.length === 0) {
        rawFields = [{ name: 'name', type: 'string', required: true }]
        output.info('No fields specified — added default "name" field')
      }

      const fields = buildFields(rawFields)

      output.info(`Generating service "${serviceName}"...`)
      generateService({ name: serviceName, fields, projectRoot })
      output.success(`Service "${serviceName}" generated successfully!`)
      output.info('Next steps:')
      console.log('  1. Review the generated files')
      console.log('  2. Run migrations: pnpm db:migrate')
      console.log('  3. Restart the dev server: pnpm dev')
    } catch (err) {
      output.error(err instanceof Error ? err.message : String(err))
      process.exitCode = 1
    }
  }
}
