// Generated by feathers-baas. Safe to edit.
import { Command, Option } from 'clipanion'
import { input } from '@inquirer/prompts'
import { resolve } from 'node:path'
import { generateHook } from '../generators/hook.generator.js'
import * as output from '../utils/output.js'

export class GenerateHookCommand extends Command {
  static override paths = [['generate', 'hook']]

  static override usage = Command.Usage({
    description: 'Generate a new Feathers hook',
    examples: [
      ['Interactive mode', 'feathers-baas generate hook'],
      ['With name', 'feathers-baas generate hook --name validate-owner'],
    ],
  })

  name = Option.String('--name,-n', { description: 'Hook name (kebab-case)', required: false })
  projectPath = Option.String('--path,-p', { description: 'Project root path', required: false })

  async execute(): Promise<void> {
    try {
      const projectRoot = resolve(this.projectPath ?? process.cwd())

      const hookName = this.name ?? await input({
        message: 'Hook name (kebab-case, e.g. "validate-owner"):',
        validate: (v) => /^[a-z][a-z0-9-]*$/.test(v) || 'Must be lowercase with hyphens only',
      })

      output.info(`Generating hook "${hookName}"...`)
      generateHook({ name: hookName, projectRoot })
      output.success(`Hook "${hookName}" generated at src/hooks/${hookName}.ts`)
    } catch (err) {
      output.error(err instanceof Error ? err.message : String(err))
      process.exitCode = 1
    }
  }
}
