// Generated by feathers-baas. Safe to edit.
import { Command, Option } from 'clipanion'
import { input, select } from '@inquirer/prompts'
import { resolve } from 'node:path'
import { execSync } from 'node:child_process'
import { generateApp, type StorageDriver, type EmailDriver } from '../generators/app.generator.js'
import * as output from '../utils/output.js'

type Database = 'postgresql' | 'mysql' | 'sqlite' | 'mongodb'

export class InitCommand extends Command {
  static override paths = [['init']]

  static override usage = Command.Usage({
    description: 'Scaffold a new feathers-baas project',
    examples: [
      ['Interactive mode', 'feathers-baas init'],
      ['With project name', 'feathers-baas init my-api'],
      ['With all flags', 'feathers-baas init my-api --database postgresql --storage s3 --email resend --install'],
    ],
  })

  projectName = Option.String({ required: false, name: 'name' })
  database = Option.String('--database,-d', { description: 'Database: postgresql, mysql, sqlite, mongodb', required: false })
  storage = Option.String('--storage', { description: 'File storage driver: local, s3, gcs, none', required: false })
  email = Option.String('--email', { description: 'Email driver: none, smtp, resend, sendgrid, brevo', required: false })
  install = Option.Boolean('--install,-i', false, { description: 'Run package manager install after scaffolding' })

  async execute(): Promise<void> {
    try {
      const projectName = this.projectName ?? await input({
        message: 'Project name:',
        validate: (v) => /^[a-z][a-z0-9-]*$/.test(v) || 'Must be lowercase with hyphens (e.g. my-api)',
      })

      const database: Database = (this.database as Database) ?? await select({
        message: 'Database:',
        choices: [
          { value: 'postgresql' as const, name: 'PostgreSQL' },
          { value: 'mysql' as const, name: 'MySQL' },
          { value: 'sqlite' as const, name: 'SQLite' },
          { value: 'mongodb' as const, name: 'MongoDB' },
        ],
        default: 'postgresql',
      })

      const storageDriver: StorageDriver = (this.storage as StorageDriver) ?? await select({
        message: 'File storage driver:',
        choices: [
          { value: 'local' as const, name: 'Local filesystem (dev/single-node)' },
          { value: 's3' as const, name: 'S3 / MinIO / LocalStack' },
          { value: 'gcs' as const, name: 'Google Cloud Storage' },
          { value: 'none' as const, name: 'None (add later)' },
        ],
        default: 'local',
      })

      const emailDriver: EmailDriver = (this.email as EmailDriver) ?? await select({
        message: 'Email driver (for auth emails — verify, reset password):',
        choices: [
          { value: 'none' as const, name: 'None (log to console)' },
          { value: 'smtp' as const, name: 'SMTP (Mailtrap, Postfix, etc.)' },
          { value: 'resend' as const, name: 'Resend' },
          { value: 'sendgrid' as const, name: 'SendGrid' },
          { value: 'brevo' as const, name: 'Brevo' },
        ],
        default: 'none',
      })

      const projectRoot = resolve(projectName)

      output.info(`Scaffolding "${projectName}" with ${database}...\n`)

      generateApp({ projectName, database, projectRoot, storageDriver, emailDriver })

      if (this.install) {
        output.info('\nInstalling dependencies...')
        const pm = detectPackageManager()
        execSync(`${pm} install`, { cwd: projectRoot, stdio: 'inherit' })
        output.success('Dependencies installed')
      }

      console.log()
      output.success(`Project "${projectName}" created!`)
      console.log()
      output.info('Next steps:')
      console.log(`  cd ${projectName}`)
      if (!this.install) {
        console.log('  pnpm install')
      }
      console.log('  # Edit .env — fill in credentials for your chosen drivers')
      console.log('  npx feathers-baas migrate   # SQL databases only — no-op for MongoDB')
      console.log('  npx feathers-baas seed      # seed default roles + admin user')
      console.log('  pnpm dev')
      console.log()
      output.info('Generate services:')
      console.log('  npx feathers-baas generate service --name posts --fields "title:string,body:text"')
    } catch (err) {
      output.error(err instanceof Error ? err.message : String(err))
      process.exitCode = 1
    }
  }
}

function detectPackageManager(): string {
  const ua = process.env['npm_config_user_agent'] ?? ''
  if (ua.startsWith('yarn')) return 'yarn'
  if (ua.startsWith('npm')) return 'npm'
  return 'pnpm'
}
