// Generated by feathers-baas. Safe to edit.
import { Command, Option } from 'clipanion'
import { input, select } from '@inquirer/prompts'
import { resolve } from 'node:path'
import { execSync } from 'node:child_process'
import { generateApp } from '../generators/app.generator.js'
import * as output from '../utils/output.js'

type Database = 'postgresql' | 'mysql' | 'sqlite' | 'mongodb'

export class InitCommand extends Command {
  static override paths = [['init']]

  static override usage = Command.Usage({
    description: 'Scaffold a new feathers-baas project',
    examples: [
      ['Interactive mode', 'feathers-baas init'],
      ['With project name', 'feathers-baas init my-api'],
      ['With all flags', 'feathers-baas init my-api --database postgresql --install'],
    ],
  })

  projectName = Option.String({ required: false, name: 'name' })
  database = Option.String('--database,-d', { description: 'Database: postgresql, mysql, sqlite, mongodb', required: false })
  install = Option.Boolean('--install,-i', false, { description: 'Run package manager install after scaffolding' })

  async execute(): Promise<void> {
    try {
      const projectName = this.projectName ?? await input({
        message: 'Project name:',
        validate: (v) => /^[a-z][a-z0-9-]*$/.test(v) || 'Must be lowercase with hyphens (e.g. my-api)',
      })

      const database: Database = (this.database as Database) ?? await select({
        message: 'Database:',
        choices: [
          { value: 'postgresql' as const, name: 'PostgreSQL' },
          { value: 'mysql' as const, name: 'MySQL' },
          { value: 'sqlite' as const, name: 'SQLite' },
          { value: 'mongodb' as const, name: 'MongoDB' },
        ],
        default: 'postgresql',
      })

      const projectRoot = resolve(projectName)

      output.info(`Scaffolding "${projectName}" with ${database}...\n`)

      generateApp({ projectName, database, projectRoot })

      if (this.install) {
        output.info('\nInstalling dependencies...')
        const pm = detectPackageManager()
        execSync(`${pm} install`, { cwd: projectRoot, stdio: 'inherit' })
        output.success('Dependencies installed')
      }

      console.log()
      output.success(`Project "${projectName}" created!`)
      console.log()
      output.info('Next steps:')
      console.log(`  cd ${projectName}`)
      if (!this.install) {
        console.log('  pnpm install')
      }
      console.log('  # Edit .env with your database URL and JWT secret')
      if (database !== 'mongodb') {
        console.log('  pnpm db:migrate')
        console.log('  pnpm db:seed')
      }
      console.log('  pnpm dev')
      console.log()
      output.info('Generate services:')
      console.log('  npx feathers-baas generate service --name posts --fields "title:string,body:text"')
    } catch (err) {
      output.error(err instanceof Error ? err.message : String(err))
      process.exitCode = 1
    }
  }
}

function detectPackageManager(): string {
  const ua = process.env['npm_config_user_agent'] ?? ''
  if (ua.startsWith('yarn')) return 'yarn'
  if (ua.startsWith('pnpm')) return 'pnpm'
  return 'npm'
}
