// Generated by feathers-baas. Safe to edit.
import { Command } from 'clipanion'
import { resolve, dirname, join } from 'node:path'
import { createRequire } from 'node:module'
import { pathToFileURL } from 'node:url'
import { existsSync, readFileSync } from 'node:fs'
import * as output from '../utils/output.js'

export class MigrateCommand extends Command {
  static override paths = [['migrate']]

  static override usage = Command.Usage({
    description: 'Run pending database migrations',
    details: `
      Runs all pending Knex migrations from ./migrations for SQL databases.
      No-op for MongoDB (schemaless).

      Idempotent — safe to run multiple times.
    `,
    examples: [['Run migrations', 'feathers-baas migrate']],
  })

  async execute(): Promise<void> {
    try {
      // Load .env (same minimal parser as SeedCommand)
      const envPath = resolve('.env')
      if (existsSync(envPath)) {
        for (const line of readFileSync(envPath, 'utf-8').split('\n')) {
          const trimmed = line.trim()
          if (!trimmed || trimmed.startsWith('#')) continue
          const eq = trimmed.indexOf('=')
          if (eq === -1) continue
          const key = trimmed.slice(0, eq).trim()
          const val = trimmed.slice(eq + 1).trim()
          if (!process.env[key]) process.env[key] = val
        }
      }

      const projectRequire = createRequire(resolve('./package.json'))

      // Register tsx at runtime so knex can import the project's .ts migrations.
      // Skipped silently if tsx isn't installed (migrations must then be .js).
      try {
        const tsxApiPath = projectRequire.resolve('tsx/esm/api')
        const { register } = await import(pathToFileURL(tsxApiPath).href)
        register()
      } catch {
        // noop
      }

      output.info('Booting app...')

      const corePkgPath = projectRequire.resolve('@feathers-baas/core/package.json')
      const corePkg = JSON.parse(readFileSync(corePkgPath, 'utf-8'))
      const coreEsmEntry = corePkg.exports['.'].import.default
      const coreEsmPath = join(dirname(corePkgPath), coreEsmEntry)
      const { createApp } = await import(pathToFileURL(coreEsmPath).href)
      const app = await createApp()

      const knex = app.get('knex')
      if (!knex) {
        output.info('No SQL database configured — skipping (MongoDB is schemaless)')
        process.exit(0)
      }

      output.info('Running migrations...\n')
      const migrationsDir = resolve('./migrations')
      const [batchNo, ran] = (await knex.migrate.latest({ directory: migrationsDir })) as [
        number,
        string[],
      ]

      if (!ran || ran.length === 0) {
        output.success('Already up to date')
      } else {
        output.success(`Batch ${batchNo} — ${ran.length} migration(s):`)
        for (const m of ran) console.log(`  • ${m}`)
      }

      await knex.destroy()
      process.exit(0)
    } catch (err) {
      output.error(err instanceof Error ? err.message : String(err))
      process.exitCode = 1
    }
  }
}
