// Generated by feathers-baas. Safe to edit.
import { Command, Option } from 'clipanion'
import { resolve, dirname, join } from 'node:path'
import { createRequire } from 'node:module'
import { pathToFileURL } from 'node:url'
import { existsSync, readFileSync } from 'node:fs'
import * as output from '../utils/output.js'

export class RollbackCommand extends Command {
  static override paths = [['rollback']]

  static override usage = Command.Usage({
    description: 'Roll back the last migration batch',
    details: `
      Rolls back the most recent migration batch (Knex's default).
      Pass --all to roll back every applied migration.
      No-op for MongoDB (schemaless).
    `,
    examples: [
      ['Roll back the last batch', 'feathers-baas rollback'],
      ['Roll back everything', 'feathers-baas rollback --all'],
    ],
  })

  all = Option.Boolean('--all', false, { description: 'Roll back all applied migrations' })

  async execute(): Promise<void> {
    try {
      const envPath = resolve('.env')
      if (existsSync(envPath)) {
        for (const line of readFileSync(envPath, 'utf-8').split('\n')) {
          const trimmed = line.trim()
          if (!trimmed || trimmed.startsWith('#')) continue
          const eq = trimmed.indexOf('=')
          if (eq === -1) continue
          const key = trimmed.slice(0, eq).trim()
          const val = trimmed.slice(eq + 1).trim()
          if (!process.env[key]) process.env[key] = val
        }
      }

      const projectRequire = createRequire(resolve('./package.json'))

      try {
        const tsxApiPath = projectRequire.resolve('tsx/esm/api')
        const { register } = await import(pathToFileURL(tsxApiPath).href)
        register()
      } catch {
        // noop
      }

      output.info('Booting app...')

      const corePkgPath = projectRequire.resolve('@feathers-baas/core/package.json')
      const corePkg = JSON.parse(readFileSync(corePkgPath, 'utf-8'))
      const coreEsmEntry = corePkg.exports['.'].import.default
      const coreEsmPath = join(dirname(corePkgPath), coreEsmEntry)
      const { createApp } = await import(pathToFileURL(coreEsmPath).href)
      const app = await createApp()

      const knex = app.get('knex')
      if (!knex) {
        output.info('No SQL database configured — skipping (MongoDB is schemaless)')
        process.exit(0)
      }

      const migrationsDir = resolve('./migrations')
      output.info(this.all ? 'Rolling back all migrations...\n' : 'Rolling back last batch...\n')
      const [batchNo, rolled] = (await knex.migrate.rollback(
        { directory: migrationsDir },
        this.all,
      )) as [number, string[]]

      if (!rolled || rolled.length === 0) {
        output.success('Already at base — nothing to roll back')
      } else {
        output.success(`Batch ${batchNo} — rolled back ${rolled.length} migration(s):`)
        for (const m of rolled) console.log(`  • ${m}`)
      }

      await knex.destroy()
      process.exit(0)
    } catch (err) {
      output.error(err instanceof Error ? err.message : String(err))
      process.exitCode = 1
    }
  }
}
