// Generated by feathers-baas. Safe to edit.
import { Command } from 'clipanion'
import { resolve } from 'node:path'
import { existsSync, readFileSync } from 'node:fs'
import * as output from '../utils/output.js'

export class SeedCommand extends Command {
  static override paths = [['seed']]

  static override usage = Command.Usage({
    description: 'Seed default roles and admin user from .env',
    details: `
      Creates the default "admin" and "user" roles, then creates an admin
      user from the ADMIN_EMAIL and ADMIN_PASSWORD environment variables.

      Idempotent — safe to run multiple times.
    `,
    examples: [['Seed the database', 'feathers-baas seed']],
  })

  async execute(): Promise<void> {
    try {
      const envPath = resolve('.env')
      if (existsSync(envPath)) {
        for (const line of readFileSync(envPath, 'utf-8').split('\n')) {
          const trimmed = line.trim()
          if (!trimmed || trimmed.startsWith('#')) continue
          const eq = trimmed.indexOf('=')
          if (eq === -1) continue
          const key = trimmed.slice(0, eq).trim()
          const val = trimmed.slice(eq + 1).trim()
          if (!process.env[key]) process.env[key] = val
        }
      }

      output.info('Booting app...')

      const { createApp, seedDatabase } = await import('@feathers-baas/core')
      const app = await createApp()

      output.info('Seeding database...\n')
      await seedDatabase(app)

      output.success('\nSeed complete!')

      process.exit(0)
    } catch (err) {
      output.error(err instanceof Error ? err.message : String(err))
      process.exitCode = 1
    }
  }
}
