// Generated by feathers-baas. Safe to edit.
import { Forbidden } from '@feathersjs/errors'
import type { HookContext } from '@feathersjs/feathers'
import { LRUCache } from 'lru-cache'
import type { Application } from '../declarations.js'
import type { Role } from '@feathers-baas/core'

type PermissionMethod = '*' | 'find' | 'get' | 'create' | 'update' | 'patch' | 'remove'

const roleCache = new LRUCache<string, Role>({
  max: 500,
  ttl: 1000 * 60 * 5,
})

export function invalidateRoleCache(roleName?: string): void {
  if (roleName) {
    roleCache.delete(roleName)
  } else {
    roleCache.clear()
  }
}

async function resolveRoles(roleNames: string[], app: Application): Promise<Role[]> {
  const missing = roleNames.filter((n) => !roleCache.has(n))

  if (missing.length > 0) {
    const svc = app.service('roles') as unknown as {
      _find(p: object): Promise<Role[] | { data: Role[]; total: number }>
    }
    const result = await svc._find({
      paginate: false,
      query: { name: { $in: missing } },
    })

    const raw: Role[] = Array.isArray(result) ? result : (result.data ?? [])
    for (const rawRole of raw) {
      const role = {
        ...rawRole,
        permissions:
          typeof rawRole.permissions === 'string'
            ? (JSON.parse(rawRole.permissions as unknown as string) as Role['permissions'])
            : rawRole.permissions,
      }
      roleCache.set(role.name, role)
    }
  }

  return roleNames.flatMap((n) => {
    const r = roleCache.get(n)
    return r ? [r] : []
  })
}

export async function checkPermissions(context: HookContext<Application>): Promise<void> {
  const user = context.params.user as { roles?: string[] } | undefined

  if (!user) {
    throw new Forbidden('No authenticated user')
  }

  const userRoles: string[] = user.roles ?? []

  if (userRoles.length === 0) {
    throw new Forbidden('User has no roles assigned')
  }

  const roles = await resolveRoles(userRoles, context.app)
  const method = context.method as PermissionMethod

  const allowed = roles.some((role) =>
    role.permissions.some(
      (p) =>
        (p.service === '*' || p.service === context.path) &&
        (p.methods.includes('*') || p.methods.includes(method)),
    ),
  )

  if (!allowed) {
    throw new Forbidden(`Role does not permit ${method} on ${context.path}`)
  }
}
