// Generated by feathers-baas. Safe to edit.
import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('files', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
    // Storage key / path within the bucket
    table.text('key').notNullable()
    // Logical bucket name (deployment-level grouping)
    table.text('bucket').notNullable()
    // Which driver stored this file ('local', 's3', 'gcs')
    table.text('driver').notNullable()
    table.text('mime_type').notNullable()
    // File size in bytes
    table.bigInteger('size').notNullable()
    table.text('original_name').notNullable()
    // FK to users.id — nullable so system uploads have no owner
    table.uuid('uploaded_by').nullable().references('id').inTable('users').onDelete('SET NULL')
    // Arbitrary metadata stored as JSONB (e.g. image dimensions, labels)
    table.jsonb('metadata').notNullable().defaultTo('{}')
    table.timestamp('created_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
  })

  // Composite index for listing files by owner + driver
  await knex.schema.raw(
    `CREATE INDEX files_uploaded_by_driver ON files (uploaded_by, driver) WHERE uploaded_by IS NOT NULL`,
  )

  // Index for prefix-based listing queries (e.g. list all files in a folder)
  await knex.schema.raw(
    `CREATE INDEX files_bucket_key ON files (bucket, key text_pattern_ops)`,
  )
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('files')
}
