// Generated by feathers-baas. Safe to edit.
// Add new services here — feathers-baas generate service will insert imports automatically.
import type { Application } from '../declarations.js'
import { configureUsers } from './users/users.service.js'
import { configureRoles } from './roles/roles.service.js'

export function configureServices(app: Application): void {
  configureUsers(app)
  configureRoles(app)
}
