// Generated by feathers-baas. Safe to edit.
import { Redis } from 'ioredis'
import {
  DriverRegistry,
  SMTPDriver,
  ResendDriver,
  SendGridDriver,
  BrevoDriver,
  createNotificationQueue,
  createNotificationWorker,
  createBullMQNotifier,
} from '@feathers-baas/plugin-notifications'
import type { Application } from '../declarations.js'
import { logger } from '../logger.js'

/**
 * Wire the notifications plugin into the Feathers app.
 *
 * Called automatically from app.ts when REDIS_URL is present in config.
 * If REDIS_URL is absent the auth notifier stub (console-log) is used instead.
 *
 * Bootstraps in this order:
 * 1. Connect to Redis (fail-fast with SELECT 0 ping)
 * 2. Build the DriverRegistry — registers SMTP or Resend if configured
 * 3. Create the BullMQ queue + worker
 * 4. Set app.set('notifier', ...) so feathers-authentication-management routes
 *    auth events through the queue
 * 5. Store worker + queue on app for graceful shutdown in index.ts
 */
export async function configureNotifications(app: Application): Promise<void> {
  const config = app.get('config')

  if (!config.redis) {
    logger.info('Notifications: REDIS_URL not set — using console-log stub')
    return
  }

  // 1. Redis connection
  const redis = new Redis(config.redis.url, { maxRetriesPerRequest: null })

  try {
    await redis.ping()
    logger.info('Notifications: Redis connected')
  } catch (err) {
    logger.error({ err }, 'Notifications: Redis connection failed')
    throw err
  }

  const notifConfig = config.notifications ?? { appUrl: 'http://localhost:3030' }

  // 2. Driver registry
  const registry = new DriverRegistry()
  const AUTH_EVENTS = [
    'auth.resend-verify-signup',
    'auth.verify-signup',
    'auth.verify-signup-set-password',
    'auth.send-reset-pwd',
    'auth.reset-pwd',
    'auth.password-change',
    'auth.identity-change',
  ] as const

  if (notifConfig.smtp) {
    const smtp = new SMTPDriver({
      url: notifConfig.smtp.url,
      fromName: notifConfig.smtp.fromName,
      fromAddress: notifConfig.smtp.fromAddress,
    })
    registry.registerDriver(smtp)
    for (const event of AUTH_EVENTS) registry.mapEvent(event, 'smtp')
    logger.info('Notifications: SMTP driver registered')
  }

  if (notifConfig.resend) {
    const resend = new ResendDriver({
      apiKey: notifConfig.resend.apiKey,
      fromName: notifConfig.resend.fromName,
      fromAddress: notifConfig.resend.fromAddress,
    })
    registry.registerDriver(resend)
    for (const event of AUTH_EVENTS) registry.mapEvent(event, 'resend')
    logger.info('Notifications: Resend driver registered')
  }

  if (notifConfig.sendgrid) {
    const sendgrid = new SendGridDriver({
      apiKey: notifConfig.sendgrid.apiKey,
      fromName: notifConfig.sendgrid.fromName,
      fromAddress: notifConfig.sendgrid.fromAddress,
    })
    registry.registerDriver(sendgrid)
    for (const event of AUTH_EVENTS) registry.mapEvent(event, 'sendgrid')
    logger.info('Notifications: SendGrid driver registered')
  }

  if (notifConfig.brevo) {
    const brevo = new BrevoDriver({
      apiKey: notifConfig.brevo.apiKey,
      fromName: notifConfig.brevo.fromName,
      fromAddress: notifConfig.brevo.fromAddress,
    })
    registry.registerDriver(brevo)
    for (const event of AUTH_EVENTS) registry.mapEvent(event, 'brevo')
    logger.info('Notifications: Brevo driver registered')
  }

  if (registry.listDriverNames().length === 0) {
    logger.warn(
      'Notifications: REDIS_URL is set but no email driver configured ' +
      '(set SMTP_URL or RESEND_API_KEY) — auth emails will be no-ops',
    )
  }

  // 3. Queue + worker
  const queue = createNotificationQueue(redis)
  const worker = createNotificationWorker(registry, redis, { concurrency: 5 })

  // 4. Wire the notifier into feathers-authentication-management
  app.set('notifier', createBullMQNotifier({ queue, registry, appUrl: notifConfig.appUrl }))

  // 5. Store for graceful shutdown
  app.set('notificationQueue', queue)
  app.set('notificationWorker', worker)

  logger.info('Notifications: BullMQ queue and worker started')
}
