// Generated by feathers-baas. Safe to edit.
import { Redis } from 'ioredis'
import {
  DriverRegistry,
  SMTPDriver,
  ResendDriver,
  SendGridDriver,
  BrevoDriver,
  createNotificationQueue,
  createNotificationWorker,
  createBullMQNotifier,
  createDirectNotifier,
} from '@feathers-baas/plugin-notifications'
import type { Application } from '../declarations.js'
import type { AppConfiguration } from '../configuration.js'
import { logger } from '../logger.js'

const AUTH_EVENTS = [
  'auth.resend-verify-signup',
  'auth.verify-signup',
  'auth.verify-signup-set-password',
  'auth.send-reset-pwd',
  'auth.reset-pwd',
  'auth.password-change',
  'auth.identity-change',
] as const

function buildDriverRegistry(notifConfig: NonNullable<AppConfiguration['notifications']>): DriverRegistry {
  const registry = new DriverRegistry()

  if (notifConfig.smtp) {
    const smtp = new SMTPDriver({
      url: notifConfig.smtp.url,
      fromName: notifConfig.smtp.fromName,
      fromAddress: notifConfig.smtp.fromAddress,
    })
    registry.registerDriver(smtp)
    for (const event of AUTH_EVENTS) registry.mapEvent(event, 'smtp')
    logger.info('Notifications: SMTP driver registered')
  }

  if (notifConfig.resend) {
    const resend = new ResendDriver({
      apiKey: notifConfig.resend.apiKey,
      fromName: notifConfig.resend.fromName,
      fromAddress: notifConfig.resend.fromAddress,
    })
    registry.registerDriver(resend)
    for (const event of AUTH_EVENTS) registry.mapEvent(event, 'resend')
    logger.info('Notifications: Resend driver registered')
  }

  if (notifConfig.sendgrid) {
    const sendgrid = new SendGridDriver({
      apiKey: notifConfig.sendgrid.apiKey,
      fromName: notifConfig.sendgrid.fromName,
      fromAddress: notifConfig.sendgrid.fromAddress,
    })
    registry.registerDriver(sendgrid)
    for (const event of AUTH_EVENTS) registry.mapEvent(event, 'sendgrid')
    logger.info('Notifications: SendGrid driver registered')
  }

  if (notifConfig.brevo) {
    const brevo = new BrevoDriver({
      apiKey: notifConfig.brevo.apiKey,
      fromName: notifConfig.brevo.fromName,
      fromAddress: notifConfig.brevo.fromAddress,
    })
    registry.registerDriver(brevo)
    for (const event of AUTH_EVENTS) registry.mapEvent(event, 'brevo')
    logger.info('Notifications: Brevo driver registered')
  }

  return registry
}

/**
 * Wire the notifications plugin into the Feathers app.
 *
 * Two modes:
 * - **With Redis**: BullMQ queue + worker for reliable async delivery with retries.
 *   Best for production. Requires REDIS_URL.
 * - **Without Redis**: Direct send — drivers are called synchronously in the
 *   request path. Suitable for development and API-based drivers (Brevo,
 *   Resend, SendGrid). SMTP should use the queue mode for reliability.
 *
 * If no driver env vars are configured at all, falls back to console-log stub.
 */
export async function configureNotifications(app: Application): Promise<void> {
  const config = app.get('config')
  const notifConfig = config.notifications ?? { appUrl: 'http://localhost:3030' }

  const registry = buildDriverRegistry(notifConfig)

  if (registry.listDriverNames().length === 0) {
    logger.info('Notifications: no email driver configured — using console-log stub')
    return
  }

  // With Redis — async delivery via BullMQ
  if (config.redis) {
    const redisOpts = { maxRetriesPerRequest: null } as const
    const queueRedis = new Redis(config.redis.url, redisOpts)
    const workerRedis = new Redis(config.redis.url, redisOpts)

    try {
      await queueRedis.ping()
      logger.info('Notifications: Redis connected')
    } catch (err) {
      logger.error({ err }, 'Notifications: Redis connection failed')
      throw err
    }

    const queue = createNotificationQueue(queueRedis)
    const worker = createNotificationWorker(registry, workerRedis, { concurrency: 5 })

    app.set('notifier', createBullMQNotifier({ queue, registry, appUrl: notifConfig.appUrl }))
    app.set('notificationQueue', queue)
    app.set('notificationWorker', worker)

    logger.info('Notifications: BullMQ queue and worker started')
    return
  }

  // Without Redis — direct synchronous send
  app.set('notifier', createDirectNotifier({ registry, appUrl: notifConfig.appUrl }))
  logger.info('Notifications: direct mode (no Redis) — emails sent synchronously')
}
