// Generated by feathers-baas. Safe to edit.
// feathers-baas generate service will add service type entries here automatically.
export type { Application } from '@feathers-baas/core'

export interface ServiceTypes {}
