// Generated by feathers-baas. Safe to edit.
import { Storage } from '@google-cloud/storage'
import type { Readable } from 'node:stream'
import type { FileDriver, FileMeta, PutResult, FileListEntry } from '../types.js'

export interface GCSDriverOptions {
  bucket: string
  /** GCP project ID. Defaults to GCLOUD_PROJECT env var. */
  projectId?: string
  /** Path to a service-account key file. Omit to use ADC. */
  keyFilename?: string
}

/**
 * Google Cloud Storage driver.
 * Uses streaming write/read — no in-memory buffering.
 * Signed URLs use V4 signing and require appropriate IAM permissions.
 */
export class GCSDriver implements FileDriver {
  private readonly storage: Storage
  private readonly gcsBucket: ReturnType<Storage['bucket']>

  constructor(private readonly opts: GCSDriverOptions) {
    this.storage = new Storage({
      projectId: opts.projectId,
      keyFilename: opts.keyFilename,
    })
    this.gcsBucket = this.storage.bucket(opts.bucket)
  }

  async put(key: string, stream: Readable, meta: FileMeta): Promise<PutResult> {
    const file = this.gcsBucket.file(key)
    const ws = file.createWriteStream({
      metadata: { contentType: meta.mimeType },
      resumable: false,
    })
    await new Promise<void>((resolve, reject) => {
      stream.pipe(ws).on('finish', resolve).on('error', reject)
    })
    const [metadata] = await file.getMetadata()
    return {
      key,
      size: Number(metadata['size'] ?? meta.size ?? 0),
    }
  }

  async get(key: string): Promise<Readable> {
    return this.gcsBucket.file(key).createReadStream()
  }

  async delete(key: string): Promise<void> {
    await this.gcsBucket.file(key).delete()
  }

  async signUrl(key: string, expiresIn: number): Promise<string> {
    const [url] = await this.gcsBucket.file(key).getSignedUrl({
      action: 'read',
      version: 'v4',
      expires: Date.now() + expiresIn * 1000,
    })
    return url
  }

  async list(prefix: string): Promise<FileListEntry[]> {
    const [files] = await this.gcsBucket.getFiles({ prefix })
    return files.map((f) => ({
      key: f.name,
      size: Number(f.metadata['size'] ?? 0),
      lastModified: new Date((f.metadata['updated'] as string | undefined) ?? Date.now()),
    }))
  }
}
