// Generated by feathers-baas. Safe to edit.
import { createReadStream, createWriteStream } from 'node:fs'
import { mkdir, unlink, stat, readdir } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { pipeline } from 'node:stream/promises'
import type { Readable } from 'node:stream'
import * as jwt from 'jsonwebtoken'
import type { FileDriver, FileMeta, PutResult, FileListEntry } from '../types.js'

export interface LocalDriverOptions {
  /** Absolute path to the directory where files will be stored. */
  directory: string
  /** Secret used to sign download tokens (same as jwtSecret in app config). */
  jwtSecret: string
  /** Base URL of the running server, e.g. http://localhost:3030 */
  baseUrl: string
}

/**
 * Local-filesystem storage driver.
 * Suitable for development and single-node production deployments.
 *
 * Signed URLs are JWT-protected download tokens — validate them in a
 * dedicated download endpoint (not part of this driver).
 */
export class LocalDriver implements FileDriver {
  constructor(private readonly opts: LocalDriverOptions) {}

  private fullPath(key: string): string {
    return join(this.opts.directory, key)
  }

  async put(key: string, stream: Readable, _meta: FileMeta): Promise<PutResult> {
    const dest = this.fullPath(key)
    await mkdir(dirname(dest), { recursive: true })
    const ws = createWriteStream(dest)
    await pipeline(stream, ws)
    const { size } = await stat(dest)
    return { key, size }
  }

  async get(key: string): Promise<Readable> {
    return createReadStream(this.fullPath(key))
  }

  async delete(key: string): Promise<void> {
    await unlink(this.fullPath(key))
  }

  async signUrl(key: string, expiresIn: number): Promise<string> {
    const token = jwt.sign({ key }, this.opts.jwtSecret, {
      expiresIn,
      algorithm: 'HS256',
    })
    return `${this.opts.baseUrl}/files/download?token=${encodeURIComponent(token)}`
  }

  async list(prefix: string): Promise<FileListEntry[]> {
    const dir = join(this.opts.directory, prefix)
    let entries: { isFile(): boolean; name: string }[]
    try {
      entries = await readdir(dir, { withFileTypes: true }) as unknown as { isFile(): boolean; name: string }[]
    } catch {
      return []
    }
    const results = await Promise.all(
      entries
        .filter((e) => e.isFile())
        .map(async (e) => {
          const entryKey = join(prefix, e.name)
          const { size, mtime } = await stat(join(this.opts.directory, entryKey))
          return { key: entryKey, size, lastModified: mtime } satisfies FileListEntry
        }),
    )
    return results
  }
}
