// Generated by feathers-baas. Safe to edit.
import {
  S3Client,
  GetObjectCommand,
  DeleteObjectCommand,
  ListObjectsV2Command,
} from '@aws-sdk/client-s3'
import { Upload } from '@aws-sdk/lib-storage'
import { getSignedUrl } from '@aws-sdk/s3-request-presigner'
import type { Readable } from 'node:stream'
import type { FileDriver, FileMeta, PutResult, FileListEntry } from '../types.js'

export interface S3DriverOptions {
  bucket: string
  region: string
  /** If omitted, the SDK picks up credentials from the environment / instance profile. */
  accessKeyId?: string
  secretAccessKey?: string
  /** Override endpoint for MinIO / LocalStack compatibility. */
  endpoint?: string
  /** Force path-style (required for MinIO). Default: false. */
  forcePathStyle?: boolean
}

/**
 * AWS S3 (and S3-compatible) storage driver.
 * Uses multipart upload for all files via @aws-sdk/lib-storage — handles
 * large files efficiently without buffering.
 */
export class S3Driver implements FileDriver {
  private readonly client: S3Client

  constructor(private readonly opts: S3DriverOptions) {
    this.client = new S3Client({
      region: opts.region,
      ...(opts.accessKeyId && opts.secretAccessKey
        ? {
            credentials: {
              accessKeyId: opts.accessKeyId,
              secretAccessKey: opts.secretAccessKey,
            },
          }
        : {}),
      ...(opts.endpoint ? { endpoint: opts.endpoint } : {}),
      ...(opts.forcePathStyle ? { forcePathStyle: true } : {}),
    })
  }

  async put(key: string, stream: Readable, meta: FileMeta): Promise<PutResult> {
    const upload = new Upload({
      client: this.client,
      params: {
        Bucket: this.opts.bucket,
        Key: key,
        Body: stream,
        ContentType: meta.mimeType,
      },
    })
    await upload.done()
    // Size comes from the upload stream; fall back to provided meta.size
    return { key, size: meta.size ?? 0 }
  }

  async get(key: string): Promise<Readable> {
    const { Body } = await this.client.send(
      new GetObjectCommand({ Bucket: this.opts.bucket, Key: key }),
    )
    if (!Body) throw new Error(`S3: empty body for key ${key}`)
    return Body as Readable
  }

  async delete(key: string): Promise<void> {
    await this.client.send(
      new DeleteObjectCommand({ Bucket: this.opts.bucket, Key: key }),
    )
  }

  async signUrl(key: string, expiresIn: number): Promise<string> {
    return getSignedUrl(
      this.client,
      new GetObjectCommand({ Bucket: this.opts.bucket, Key: key }),
      { expiresIn },
    )
  }

  async list(prefix: string): Promise<FileListEntry[]> {
    const { Contents = [] } = await this.client.send(
      new ListObjectsV2Command({ Bucket: this.opts.bucket, Prefix: prefix }),
    )
    return Contents.map((item) => ({
      key: item.Key ?? '',
      size: item.Size ?? 0,
      lastModified: item.LastModified ?? new Date(),
    }))
  }
}
