// Generated by feathers-baas. Safe to edit.
import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  await knex.schema.createTable('users', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
    table.string('email').notNullable().unique()
    table.text('password').nullable()
    // Roles stored as a text array — denormalized by design for fast permission checks
    table.specificType('roles', 'text[]').notNullable().defaultTo('{}')
    table.boolean('is_verified').notNullable().defaultTo(false)
    table.boolean('is_active').notNullable().defaultTo(true)
    table.jsonb('oauth_ids').nullable()
    // feathers-authentication-management fields
    table.text('verify_token').nullable()
    table.string('verify_short_token').nullable()
    table.timestamp('verify_expires', { useTz: true }).nullable()
    table.jsonb('verify_changes').nullable().defaultTo('{}')
    table.text('reset_token').nullable()
    table.string('reset_short_token').nullable()
    table.timestamp('reset_expires', { useTz: true }).nullable()
    table.integer('reset_attempts').nullable().defaultTo(0)
    table.timestamp('created_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
    table.timestamp('updated_at', { useTz: true }).notNullable().defaultTo(knex.fn.now())
    table.timestamp('deleted_at', { useTz: true }).nullable()
  })

  // Index for soft-delete filtering
  await knex.schema.raw(
    `CREATE INDEX users_deleted_at_null ON users (id) WHERE deleted_at IS NULL`,
  )
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists('users')
}
