// Generated by feathers-baas. Safe to edit.
import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  // GIN index for efficient array containment queries on users.roles
  await knex.schema.raw('CREATE INDEX users_roles_gin ON users USING GIN (roles)')
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.raw('DROP INDEX IF EXISTS users_roles_gin')
}
