// Generated by feathers-baas. Safe to edit.
import { feathers } from '@feathersjs/feathers'
import {
  koa,
  rest,
  bodyParser,
  errorHandler,
  parseAuthentication,
  cors,
  serveStatic,
} from '@feathersjs/koa'
import type { Application } from './declarations.js'
import { resolveConfig } from './configuration.js'
import { logger } from './logger.js'
import { configureKnex } from './db/index.js'
import { configureAuth } from './auth/index.js'
import { configureAuthManagement } from './auth/auth-management.js'
import { configureServices } from './services/index.js'
import { configureChannels } from './channels.js'
import { configureNotifications } from './notifications/index.js'
import { configureHealth } from './health.js'
import { configureOpenApi } from './openapi.js'
import { logError } from './hooks/log-error.js'

export async function createApp(): Promise<Application> {
  const config = resolveConfig()

  const app = koa(feathers()) as Application

  // 1. Store typed config on app
  app.set('config', config)

  // 2. Security & body middleware
  // cors origin: accept array by checking request origin against allowlist
  const allowedOrigins = new Set(config.cors.origins)
  app.use(
    cors({
      origin: (ctx) => {
        const reqOrigin = ctx.request.headers['origin'] ?? ''
        return allowedOrigins.has(reqOrigin) ? reqOrigin : config.cors.origins[0] ?? ''
      },
    }),
  )
  app.use(errorHandler())
  app.use(serveStatic('.'))
  app.use(parseAuthentication())
  app.use(bodyParser())

  // 3. Health checks + OpenAPI (before auth — no token required)
  configureHealth(app)
  configureOpenApi(app)

  // 4. Transports
  app.configure(rest())

  // 5. Database
  await configureKnex(app)

  // 6. Authentication
  configureAuth(app)

  // 7. Services
  configureServices(app)

  // 8. Auth management (verification, password reset — depends on users service)
  configureAuthManagement(app)

  // 9. Channels (real-time)
  configureChannels(app)

  // 10. Notifications (BullMQ queue + driver — no-op when REDIS_URL is absent)
  await configureNotifications(app)

  // 11. App-wide error logging hook
  app.hooks({ around: { all: [logError] } })

  logger.debug('App configured')
  return app
}
