// Generated by feathers-baas. Safe to edit.
import { feathers } from '@feathersjs/feathers'
import {
  koa,
  rest,
  bodyParser,
  errorHandler,
  parseAuthentication,
  cors,
  serveStatic,
} from '@feathersjs/koa'
import type { Application } from './declarations.js'
import { resolveConfig } from './configuration.js'
import { logger } from './logger.js'
import { configureKnex, configureMysql, configureSqlite, configureMongo } from './db/index.js'
import { configureAuth } from './auth/index.js'
import { configureRefresh } from './auth/refresh.js'
import { configureAuthManagement } from './auth/auth-management.js'
import { configureServices } from './services/index.js'
import { configureChannels } from './channels.js'
import { configureNotifications } from './notifications/index.js'
import { configureHealth } from './health.js'
import { configureOpenApi } from './openapi.js'
import { installPlugins } from './plugins.js'
import { logError } from './hooks/log-error.js'

export interface CreateAppOptions {
  configureServices?: (app: Application) => void
}

export async function createApp(options?: CreateAppOptions): Promise<Application> {
  const config = resolveConfig()

  const app = koa(feathers()) as Application

  // 1. Store typed config on app
  app.set('config', config)

  // 2. Security & body middleware
  // cors origin: accept array by checking request origin against allowlist
  const allowedOrigins = new Set(config.cors.origins)
  app.use(
    cors({
      origin: (ctx) => {
        const reqOrigin = ctx.request.headers['origin'] ?? ''
        return allowedOrigins.has(reqOrigin) ? reqOrigin : config.cors.origins[0] ?? ''
      },
    }),
  )
  app.use(errorHandler())
  app.use(serveStatic('.'))
  app.use(parseAuthentication())
  // Skip body parsing for multipart — busboy streams those directly in the upload hook.
  // Raise the JSON/urlencoded limit to 10 MB for large payloads.
  app.use(bodyParser({
    jsonLimit: '10mb',
    formLimit: '10mb',
    multipart: false,
  }))

  // 3. Health checks + OpenAPI (before auth — no token required)
  configureHealth(app)
  configureOpenApi(app)

  // 4. Transports
  app.configure(rest())

  // 5. Database — auto-detect from config
  if (config.postgres) {
    await configureKnex(app)
  } else if (config.mysql) {
    await configureMysql(app)
  } else if (config.sqlite) {
    await configureSqlite(app)
  } else if (config.mongodb) {
    await configureMongo(app)
  } else {
    throw new Error('No database configured — set DATABASE_URL, MYSQL_URL, SQLITE_FILENAME, or MONGODB_URL')
  }

  // 6. Authentication
  configureAuth(app)
  configureRefresh(app)

  // 7. Services
  configureServices(app)
  options?.configureServices?.(app)

  // 8. Auth management (verification, password reset — depends on users service)
  configureAuthManagement(app)

  // 9. Channels (real-time)
  configureChannels(app)

  // 10. Notifications (BullMQ queue + driver — no-op when REDIS_URL is absent)
  await configureNotifications(app)

  // 11. Plugins (auto-discovered from package.json)
  await installPlugins(app)

  // 12. App-wide error logging hook
  app.hooks({ around: { all: [logError] } })

  logger.debug('App configured')
  return app
}
