// Generated by feathers-baas. Safe to edit.
// Channels control which real-time events are sent to which clients.
// Default: publish nothing — services must explicitly opt in.
// This is intentional to avoid leaking data by accident.
import type { RealTimeConnection } from '@feathersjs/feathers'
import type { Application } from './declarations.js'

export function configureChannels(app: Application): void {
  if (!app.channel) {
    // Realtime not configured (REST-only mode) — skip
    return
  }

  app.on('connection', (connection: RealTimeConnection) => {
    app.channel('anonymous').join(connection)
  })

  app.on('login', (_authResult: unknown, { connection }: { connection?: RealTimeConnection }) => {
    if (connection) {
      app.channel('anonymous').leave(connection)
      app.channel('authenticated').join(connection)
    }
  })

  // Each service should publish its own events explicitly.
  // Example: app.service('users').publish(() => app.channel('authenticated'))
}
