// Generated by feathers-baas. Safe to edit.
import { Type, type Static } from '@feathersjs/typebox'
import { Value } from '@sinclair/typebox/value'

const AppConfigurationSchema = Type.Object({
  host: Type.String({ default: '0.0.0.0' }),
  port: Type.Number({ default: 3030 }),
  nodeEnv: Type.Union([
    Type.Literal('development'),
    Type.Literal('test'),
    Type.Literal('production'),
  ], { default: 'development' }),

  postgres: Type.Object({
    url: Type.String({ minLength: 1 }),
  }),

  jwtSecret: Type.String({ minLength: 32 }),
  jwtExpiry: Type.String({ default: '15m' }),
  jwtRefreshExpiry: Type.String({ default: '7d' }),

  argon2: Type.Object({
    memoryCost: Type.Number({ default: 65536 }),
    timeCost: Type.Number({ default: 3 }),
    parallelism: Type.Number({ default: 4 }),
  }),

  cors: Type.Object({
    origins: Type.Array(Type.String(), { default: ['http://localhost:3000'] }),
  }),

  adminEmail: Type.Optional(Type.String()),
  adminPassword: Type.Optional(Type.String()),
})

export type AppConfiguration = Static<typeof AppConfigurationSchema>

export function resolveConfig(): AppConfiguration {
  const raw = {
    host: process.env['HOST'] ?? '0.0.0.0',
    port: process.env['PORT'] ? Number(process.env['PORT']) : 3030,
    nodeEnv: process.env['NODE_ENV'] ?? 'development',

    postgres: {
      url: process.env['DATABASE_URL'] ?? '',
    },

    jwtSecret: process.env['JWT_SECRET'] ?? '',
    jwtExpiry: process.env['JWT_EXPIRY'] ?? '15m',
    jwtRefreshExpiry: process.env['JWT_REFRESH_EXPIRY'] ?? '7d',

    argon2: {
      memoryCost: process.env['ARGON2_MEMORY_COST']
        ? Number(process.env['ARGON2_MEMORY_COST'])
        : 65536,
      timeCost: process.env['ARGON2_TIME_COST']
        ? Number(process.env['ARGON2_TIME_COST'])
        : 3,
      parallelism: process.env['ARGON2_PARALLELISM']
        ? Number(process.env['ARGON2_PARALLELISM'])
        : 4,
    },

    cors: {
      origins: process.env['CORS_ORIGINS']
        ? process.env['CORS_ORIGINS'].split(',').map((s) => s.trim())
        : ['http://localhost:3000'],
    },

    adminEmail: process.env['ADMIN_EMAIL'],
    adminPassword: process.env['ADMIN_PASSWORD'],
  }

  if (!Value.Check(AppConfigurationSchema, raw)) {
    const errors = [...Value.Errors(AppConfigurationSchema, raw)]
    const messages = errors.map((e) => `  ${e.path}: ${e.message}`).join('\n')
    throw new Error(`Invalid configuration:\n${messages}`)
  }

  return raw as AppConfiguration
}
