// Generated by feathers-baas. Safe to edit.
import type { Knex } from 'knex'
import type { Application as KoaApplication } from '@feathersjs/koa'
import type { AuthenticationService } from '@feathersjs/authentication'
import type { Worker, Queue } from 'bullmq'
import type { AppConfiguration } from './configuration.js'
import type { UsersClass } from './services/users/users.class.js'
import type { RolesClass } from './services/roles/roles.class.js'
import type { NotificationJob } from '@feathers-baas/plugin-notifications'

export type { AppConfiguration }

export interface ServiceTypes {
  authentication: AuthenticationService
  users: UsersClass
  roles: RolesClass
}

/**
 * Signature of the notifier function consumed by feathers-authentication-management.
 * Set `app.set('notifier', fn)` in your plugin setup to replace the default stub.
 * The stub logs to console; the real implementation is in @feathers-baas/plugin-notifications.
 */
export type AppNotifierFn = (
  type: string,
  user: Record<string, unknown>,
  notifierOptions?: Record<string, unknown>,
) => Promise<void>

export interface Configuration {
  knex: Knex
  config: AppConfiguration
  // Auth settings stored by AuthenticationService
  authentication: Record<string, unknown>
  /**
   * Optional notifier override — set by @feathers-baas/plugin-notifications.
   * Falls back to console-logging stub when not configured.
   */
  notifier?: AppNotifierFn
  /**
   * BullMQ worker — set when REDIS_URL is configured.
   * Call worker.close() during graceful shutdown.
   */
  notificationWorker?: Worker<NotificationJob>
  /**
   * BullMQ queue — set when REDIS_URL is configured.
   * Call queue.close() during graceful shutdown.
   */
  notificationQueue?: Queue<NotificationJob>
}

// Application is the @feathersjs/koa Application with our typed services and config
export type Application = KoaApplication<ServiceTypes, Configuration>
