// Generated by feathers-baas. Safe to edit.
import type { Knex } from 'knex'
import type { Application as KoaApplication } from '@feathersjs/koa'
import type { AuthenticationService } from '@feathersjs/authentication'
import type { AppConfiguration } from './configuration.js'
import type { UsersClass } from './services/users/users.class.js'
import type { RolesClass } from './services/roles/roles.class.js'

export type { AppConfiguration }

export interface ServiceTypes {
  authentication: AuthenticationService
  users: UsersClass
  roles: RolesClass
}

export interface Configuration {
  knex: Knex
  config: AppConfiguration
  // Auth settings stored by AuthenticationService
  authentication: Record<string, unknown>
}

// Application is the @feathersjs/koa Application with our typed services and config
export type Application = KoaApplication<ServiceTypes, Configuration>
