// Generated by feathers-baas. Safe to edit.
import type { Knex } from 'knex'
import type { MongoClient, Db } from 'mongodb'
import type { Application as KoaApplication } from '@feathersjs/koa'
import type { AuthenticationService } from '@feathersjs/authentication'
import type { Worker, Queue } from 'bullmq'
import type { AppConfiguration } from './configuration.js'
import type { UsersClass, UsersMongoClass } from './services/users/users.class.js'
import type { RolesClass, RolesMongoClass } from './services/roles/roles.class.js'
import type { NotificationJob } from '@feathers-baas/plugin-notifications'

export type { AppConfiguration }

export interface ServiceTypes {
  authentication: AuthenticationService
  users: UsersClass | UsersMongoClass
  roles: RolesClass | RolesMongoClass
}

export type AppNotifierFn = (
  type: string,
  user: Record<string, unknown>,
  notifierOptions?: Record<string, unknown>,
) => Promise<void>

export interface Configuration {
  knex?: Knex
  config: AppConfiguration
  authentication: Record<string, unknown>
  notifier?: AppNotifierFn
  notificationWorker?: Worker<NotificationJob>
  notificationQueue?: Queue<NotificationJob>
  mongoClient?: MongoClient
  mongoDb?: Db
}

export type Application = KoaApplication<ServiceTypes, Configuration>
