// Generated by feathers-baas. Safe to edit.
import type { Application } from './declarations.js'

interface CheckResult {
  name: string
  status: 'ok' | 'error'
  message?: string
}

export function configureHealth(app: Application): void {
  const koaApp = app as unknown as { use(mw: (ctx: KoaContext, next: () => Promise<void>) => Promise<void>): void }

  koaApp.use(async (ctx: KoaContext, next) => {
    if (ctx.path === '/health') {
      ctx.status = 200
      ctx.body = { status: 'ok' }
      return
    }

    if (ctx.path === '/health/ready') {
      const checks: CheckResult[] = []

      // DB check (Knex-based)
      const knex = app.get('knex')
      if (knex) {
        try {
          await knex.raw('SELECT 1')
          checks.push({ name: 'database', status: 'ok' })
        } catch (err) {
          checks.push({ name: 'database', status: 'error', message: (err as Error).message })
        }
      }

      // MongoDB check
      const mongoDb = app.get('mongoDb')
      if (mongoDb) {
        try {
          await mongoDb.command({ ping: 1 })
          checks.push({ name: 'mongodb', status: 'ok' })
        } catch (err) {
          checks.push({ name: 'mongodb', status: 'error', message: (err as Error).message })
        }
      }

      // Redis check (only if queue is configured)
      const queue = app.get('notificationQueue')
      if (queue) {
        try {
          const client = await queue.client
          await client.ping()
          checks.push({ name: 'redis', status: 'ok' })
        } catch (err) {
          checks.push({ name: 'redis', status: 'error', message: (err as Error).message })
        }
      }

      const degraded = checks.some((c) => c.status === 'error')
      ctx.status = degraded ? 503 : 200
      ctx.body = { status: degraded ? 'degraded' : 'ok', checks }
      return
    }

    await next()
  })
}

interface KoaContext {
  path: string
  status: number
  body: unknown
}
