// Generated by feathers-baas. Safe to edit.
import 'dotenv/config'
import { createApp } from './app.js'
import { logger } from './logger.js'

const startTime = Date.now()

const app = await createApp()
const config = app.get('config')
const server = await app.listen(config.port)

const elapsed = Date.now() - startTime
logger.info(
  { host: config.host, port: config.port, env: config.nodeEnv, startupMs: elapsed },
  'Server listening',
)

// ─── Graceful shutdown ────────────────────────────────────────────────────────

async function shutdown(signal: string): Promise<void> {
  logger.info({ signal }, 'Shutdown signal received')

  server.close(async () => {
    try {
      // Drain BullMQ worker first so in-flight jobs complete before closing Redis
      const worker = app.get('notificationWorker')
      const queue = app.get('notificationQueue')
      if (worker) {
        await worker.close()
        logger.info('Notification worker drained')
      }
      if (queue) {
        await queue.close()
        logger.info('Notification queue closed')
      }

      const knex = app.get('knex')
      await knex.destroy()
      logger.info('Database connections closed')
    } catch (err) {
      logger.error({ err }, 'Error during shutdown')
    }
    logger.info('Server stopped')
    process.exit(0)
  })

  // Force exit after 30 seconds
  setTimeout(() => {
    logger.error('Forced shutdown after timeout')
    process.exit(1)
  }, 30_000).unref()
}

process.on('SIGTERM', () => { void shutdown('SIGTERM') })
process.on('SIGINT', () => { void shutdown('SIGINT') })
