// Generated by feathers-baas. Safe to edit.
import pino from 'pino'

const isDev = process.env['NODE_ENV'] !== 'production' && process.env['NODE_ENV'] !== 'test'

export const logger = pino({
  level: process.env['LOG_LEVEL'] ?? (isDev ? 'debug' : 'info'),
  ...(isDev
    ? {
        transport: {
          target: 'pino-pretty',
          options: { colorize: true, translateTime: 'SYS:HH:MM:ss' },
        },
      }
    : {}),
  redact: {
    paths: ['*.password', '*.passwordHash', '*.token', '*.secret', '*.authorization'],
    censor: '[REDACTED]',
  },
})
