// Generated by feathers-baas. Safe to edit.
import type { TObject } from '@sinclair/typebox'
import type { Application } from './declarations.js'

export interface ServiceSchemas {
  main: TObject
  data?: TObject
  patch?: TObject
  query?: TObject
  methods: string[]
  // Per-path operation overrides merged after the auto-generated operations.
  // Key is the full path (e.g. '/files'); value is a map of HTTP method → operation object.
  // Use this when a standard CRUD operation needs a non-JSON request body (e.g. multipart upload).
  customPaths?: Record<string, Record<string, unknown>>
}

const schemaRegistry = new Map<string, ServiceSchemas>()

export function registerServiceSchemas(serviceName: string, schemas: ServiceSchemas): void {
  schemaRegistry.set(serviceName, schemas)
}

function stripTypebox(schema: TObject): Record<string, unknown> {
  const { $id, kind, ...rest } = schema as Record<string, unknown>
  const cleaned = { ...rest } as Record<string, unknown>
  if (cleaned['properties'] && typeof cleaned['properties'] === 'object') {
    const props = { ...(cleaned['properties'] as Record<string, unknown>) }
    for (const [key, val] of Object.entries(props)) {
      if (val && typeof val === 'object') {
        const { kind: _k, ...propRest } = val as Record<string, unknown>
        props[key] = propRest
      }
    }
    cleaned['properties'] = props
  }
  return cleaned
}

function buildPaths(schemas: ServiceSchemas, serviceName: string, refPrefix: string): Record<string, unknown> {
  const paths: Record<string, unknown> = {}
  const tag = serviceName
  const collectionPath = `/${serviceName}`
  const itemPath = `/${serviceName}/{id}`
  const collectionOps: Record<string, unknown> = {}
  const itemOps: Record<string, unknown> = {}

  if (schemas.methods.includes('find')) {
    collectionOps['get'] = {
      tags: [tag],
      summary: `Find ${serviceName}`,
      operationId: `find${capitalize(serviceName)}`,
      parameters: [
        { name: '$limit', in: 'query', schema: { type: 'integer' } },
        { name: '$skip', in: 'query', schema: { type: 'integer' } },
        { name: '$sort', in: 'query', schema: { type: 'object' } },
      ],
      responses: {
        '200': {
          description: 'Success',
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: {
                  total: { type: 'integer' },
                  limit: { type: 'integer' },
                  skip: { type: 'integer' },
                  data: { type: 'array', items: { $ref: `${refPrefix}${capitalize(serviceName)}` } },
                },
              },
            },
          },
        },
      },
    }
  }

  if (schemas.methods.includes('get')) {
    itemOps['get'] = {
      tags: [tag],
      summary: `Get a ${singularize(serviceName)}`,
      operationId: `get${capitalize(singularize(serviceName))}`,
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
      responses: {
        '200': {
          description: 'Success',
          content: { 'application/json': { schema: { $ref: `${refPrefix}${capitalize(serviceName)}` } } },
        },
        '404': { description: 'Not found' },
      },
    }
  }

  if (schemas.methods.includes('create') && schemas.data) {
    collectionOps['post'] = {
      tags: [tag],
      summary: `Create a ${singularize(serviceName)}`,
      operationId: `create${capitalize(singularize(serviceName))}`,
      requestBody: {
        required: true,
        content: {
          'application/json': { schema: { $ref: `${refPrefix}${capitalize(serviceName)}Data` } },
        },
      },
      responses: {
        '201': {
          description: 'Created',
          content: { 'application/json': { schema: { $ref: `${refPrefix}${capitalize(serviceName)}` } } },
        },
      },
    }
  }

  if (schemas.methods.includes('patch') && schemas.patch) {
    itemOps['patch'] = {
      tags: [tag],
      summary: `Patch a ${singularize(serviceName)}`,
      operationId: `patch${capitalize(singularize(serviceName))}`,
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
      requestBody: {
        required: true,
        content: {
          'application/json': { schema: { $ref: `${refPrefix}${capitalize(serviceName)}Patch` } },
        },
      },
      responses: {
        '200': {
          description: 'Success',
          content: { 'application/json': { schema: { $ref: `${refPrefix}${capitalize(serviceName)}` } } },
        },
        '404': { description: 'Not found' },
      },
    }
  }

  if (schemas.methods.includes('remove')) {
    itemOps['delete'] = {
      tags: [tag],
      summary: `Remove a ${singularize(serviceName)}`,
      operationId: `remove${capitalize(singularize(serviceName))}`,
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
      responses: {
        '200': {
          description: 'Success',
          content: { 'application/json': { schema: { $ref: `${refPrefix}${capitalize(serviceName)}` } } },
        },
        '404': { description: 'Not found' },
      },
    }
  }

  if (Object.keys(collectionOps).length > 0) paths[collectionPath] = collectionOps
  if (Object.keys(itemOps).length > 0) paths[itemPath] = itemOps

  return paths
}

export function generateOpenApiSpec(app: Application): Record<string, unknown> {
  const config = app.get('config')
  const refPrefix = '#/components/schemas/'

  const schemas: Record<string, unknown> = {}
  const paths: Record<string, unknown> = {}

  for (const [serviceName, serviceSchemas] of schemaRegistry) {
    const name = capitalize(serviceName)
    schemas[name] = stripTypebox(serviceSchemas.main)
    if (serviceSchemas.data) schemas[`${name}Data`] = stripTypebox(serviceSchemas.data)
    if (serviceSchemas.patch) schemas[`${name}Patch`] = stripTypebox(serviceSchemas.patch)
    if (serviceSchemas.query) schemas[`${name}Query`] = stripTypebox(serviceSchemas.query)

    Object.assign(paths, buildPaths(serviceSchemas, serviceName, refPrefix))

    // Merge any custom path overrides (e.g. multipart upload replacing the auto-generated POST)
    if (serviceSchemas.customPaths) {
      for (const [path, ops] of Object.entries(serviceSchemas.customPaths)) {
        paths[path] = { ...(paths[path] as Record<string, unknown> ?? {}), ...ops }
      }
    }
  }

  // ─── Authentication ───────────────────────────────────────────────────────

  paths['/authentication'] = {
    post: {
      tags: ['authentication'],
      summary: 'Login',
      operationId: 'authenticate',
      security: [],
      requestBody: {
        required: true,
        content: {
          'application/json': {
            schema: {
              type: 'object',
              required: ['strategy'],
              properties: {
                strategy: { type: 'string', enum: ['local', 'jwt'] },
                email: { type: 'string', format: 'email' },
                password: { type: 'string' },
                accessToken: { type: 'string' },
              },
            },
          },
        },
      },
      responses: {
        '201': {
          description: 'Authenticated',
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: {
                  accessToken: { type: 'string', description: 'Short-lived JWT access token' },
                  refreshToken: { type: 'string', description: 'Long-lived refresh token (also set as HTTP-only cookie)' },
                  authentication: { type: 'object' },
                  user: { $ref: `${refPrefix}Users` },
                },
              },
            },
          },
        },
        '401': { description: 'Not authenticated' },
      },
    },
    delete: {
      tags: ['authentication'],
      summary: 'Logout',
      operationId: 'logout',
      responses: {
        '200': { description: 'Logged out — refresh cookie cleared' },
        '401': { description: 'Not authenticated' },
      },
    },
  }

  paths['/authentication/refresh'] = {
    post: {
      tags: ['authentication'],
      summary: 'Refresh access token',
      operationId: 'refreshToken',
      security: [],
      requestBody: {
        required: true,
        content: {
          'application/json': {
            schema: {
              type: 'object',
              required: ['refreshToken'],
              properties: {
                refreshToken: { type: 'string', description: 'Long-lived refresh token from login response' },
              },
            },
          },
        },
      },
      responses: {
        '200': {
          description: 'New access token issued',
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: {
                  accessToken: { type: 'string' },
                  user: { $ref: `${refPrefix}Users` },
                },
              },
            },
          },
        },
        '401': { description: 'Invalid or expired refresh token' },
      },
    },
  }

  // ─── Auth management (email verify, password reset) ───────────────────────

  paths['/authManagement'] = {
    post: {
      tags: ['authManagement'],
      summary: 'Auth management actions',
      operationId: 'authManagement',
      security: [],
      requestBody: {
        required: true,
        content: {
          'application/json': {
            schema: {
              type: 'object',
              required: ['action', 'value'],
              discriminator: { propertyName: 'action' },
              properties: {
                action: {
                  type: 'string',
                  enum: [
                    'verifySignupLong',
                    'verifySignupShort',
                    'resendVerifySignup',
                    'sendResetPwd',
                    'resetPwdLong',
                    'resetPwdShort',
                    'passwordChange',
                    'identityChange',
                  ],
                  description: [
                    'verifySignupLong   — verify email with long token from link',
                    'verifySignupShort  — verify email with short code',
                    'resendVerifySignup — re-send verification email',
                    'sendResetPwd       — send password reset email',
                    'resetPwdLong       — reset password with long token',
                    'resetPwdShort      — reset password with short code',
                    'passwordChange     — change password (requires current password)',
                    'identityChange     — change email address (requires password)',
                  ].join('\n'),
                },
                value: {
                  type: 'object',
                  description: 'Payload varies by action',
                  examples: {
                    verifySignupLong:   { value: { value: { token: '<verifyToken>' } } },
                    sendResetPwd:       { value: { value: { email: 'user@example.com' } } },
                    resetPwdLong:       { value: { value: { token: '<resetToken>', password: 'newPassword123' } } },
                    passwordChange:     { value: { value: { user: { email: 'user@example.com' }, oldPassword: 'old', password: 'new' } } },
                  },
                },
              },
            },
          },
        },
      },
      responses: {
        '201': { description: 'Action completed successfully' },
        '400': { description: 'Bad request — invalid token, expired token, or validation error' },
      },
    },
  }

  return {
    openapi: '3.1.0',
    info: {
      title: 'feathers-baas API',
      version: '0.0.1',
      description: 'Auto-generated from TypeBox schemas',
    },
    servers: [
      { url: `http://${config.host === '0.0.0.0' ? 'localhost' : config.host}:${config.port}` },
    ],
    paths,
    components: {
      schemas,
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
    },
    security: [{ bearerAuth: [] }],
  }
}

const SCALAR_HTML = `<!DOCTYPE html>
<html>
<head>
  <title>feathers-baas API Docs</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
  <script id="api-reference" data-url="/openapi.json"></script>
  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
</body>
</html>`

export function configureOpenApi(app: Application): void {
  // Expose registerServiceSchemas on the app so external plugins (e.g. plugin-files)
  // can register their schemas without importing @feathers-baas/core directly.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ;(app as any).set('registerServiceSchemas', registerServiceSchemas)

  const koaApp = app as unknown as {
    use(mw: (ctx: { path: string; status: number; body: unknown; type: string }, next: () => Promise<void>) => Promise<void>): void
  }

  koaApp.use(async (ctx, next) => {
    if (ctx.path === '/openapi.json') {
      ctx.status = 200
      ctx.type = 'application/json'
      ctx.body = generateOpenApiSpec(app)
      return
    }

    if (ctx.path === '/docs') {
      ctx.status = 200
      ctx.type = 'text/html'
      ctx.body = SCALAR_HTML
      return
    }

    await next()
  })
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function singularize(s: string): string {
  if (s.endsWith('s')) return s.slice(0, -1)
  return s
}
