// Generated by feathers-baas. Safe to edit.
import type { TObject } from '@sinclair/typebox'
import type { Application } from './declarations.js'

export interface ServiceSchemas {
  main: TObject
  data?: TObject
  patch?: TObject
  query?: TObject
  methods: string[]
}

const schemaRegistry = new Map<string, ServiceSchemas>()

export function registerServiceSchemas(serviceName: string, schemas: ServiceSchemas): void {
  schemaRegistry.set(serviceName, schemas)
}

function stripTypebox(schema: TObject): Record<string, unknown> {
  const { $id, kind, ...rest } = schema as Record<string, unknown>
  const cleaned = { ...rest } as Record<string, unknown>
  if (cleaned['properties'] && typeof cleaned['properties'] === 'object') {
    const props = { ...(cleaned['properties'] as Record<string, unknown>) }
    for (const [key, val] of Object.entries(props)) {
      if (val && typeof val === 'object') {
        const { kind: _k, ...propRest } = val as Record<string, unknown>
        props[key] = propRest
      }
    }
    cleaned['properties'] = props
  }
  return cleaned
}

function buildPaths(schemas: ServiceSchemas, serviceName: string, refPrefix: string): Record<string, unknown> {
  const paths: Record<string, unknown> = {}
  const tag = serviceName
  const collectionPath = `/${serviceName}`
  const itemPath = `/${serviceName}/{id}`
  const collectionOps: Record<string, unknown> = {}
  const itemOps: Record<string, unknown> = {}

  if (schemas.methods.includes('find')) {
    collectionOps['get'] = {
      tags: [tag],
      summary: `Find ${serviceName}`,
      operationId: `find${capitalize(serviceName)}`,
      parameters: [
        { name: '$limit', in: 'query', schema: { type: 'integer' } },
        { name: '$skip', in: 'query', schema: { type: 'integer' } },
        { name: '$sort', in: 'query', schema: { type: 'object' } },
      ],
      responses: {
        '200': {
          description: 'Success',
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: {
                  total: { type: 'integer' },
                  limit: { type: 'integer' },
                  skip: { type: 'integer' },
                  data: { type: 'array', items: { $ref: `${refPrefix}${capitalize(serviceName)}` } },
                },
              },
            },
          },
        },
      },
    }
  }

  if (schemas.methods.includes('get')) {
    itemOps['get'] = {
      tags: [tag],
      summary: `Get a ${singularize(serviceName)}`,
      operationId: `get${capitalize(singularize(serviceName))}`,
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
      responses: {
        '200': {
          description: 'Success',
          content: { 'application/json': { schema: { $ref: `${refPrefix}${capitalize(serviceName)}` } } },
        },
        '404': { description: 'Not found' },
      },
    }
  }

  if (schemas.methods.includes('create') && schemas.data) {
    collectionOps['post'] = {
      tags: [tag],
      summary: `Create a ${singularize(serviceName)}`,
      operationId: `create${capitalize(singularize(serviceName))}`,
      requestBody: {
        required: true,
        content: {
          'application/json': { schema: { $ref: `${refPrefix}${capitalize(serviceName)}Data` } },
        },
      },
      responses: {
        '201': {
          description: 'Created',
          content: { 'application/json': { schema: { $ref: `${refPrefix}${capitalize(serviceName)}` } } },
        },
      },
    }
  }

  if (schemas.methods.includes('patch') && schemas.patch) {
    itemOps['patch'] = {
      tags: [tag],
      summary: `Patch a ${singularize(serviceName)}`,
      operationId: `patch${capitalize(singularize(serviceName))}`,
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
      requestBody: {
        required: true,
        content: {
          'application/json': { schema: { $ref: `${refPrefix}${capitalize(serviceName)}Patch` } },
        },
      },
      responses: {
        '200': {
          description: 'Success',
          content: { 'application/json': { schema: { $ref: `${refPrefix}${capitalize(serviceName)}` } } },
        },
        '404': { description: 'Not found' },
      },
    }
  }

  if (schemas.methods.includes('remove')) {
    itemOps['delete'] = {
      tags: [tag],
      summary: `Remove a ${singularize(serviceName)}`,
      operationId: `remove${capitalize(singularize(serviceName))}`,
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
      responses: {
        '200': {
          description: 'Success',
          content: { 'application/json': { schema: { $ref: `${refPrefix}${capitalize(serviceName)}` } } },
        },
        '404': { description: 'Not found' },
      },
    }
  }

  if (Object.keys(collectionOps).length > 0) paths[collectionPath] = collectionOps
  if (Object.keys(itemOps).length > 0) paths[itemPath] = itemOps

  return paths
}

export function generateOpenApiSpec(app: Application): Record<string, unknown> {
  const config = app.get('config')
  const refPrefix = '#/components/schemas/'

  const schemas: Record<string, unknown> = {}
  const paths: Record<string, unknown> = {}

  for (const [serviceName, serviceSchemas] of schemaRegistry) {
    const name = capitalize(serviceName)
    schemas[name] = stripTypebox(serviceSchemas.main)
    if (serviceSchemas.data) schemas[`${name}Data`] = stripTypebox(serviceSchemas.data)
    if (serviceSchemas.patch) schemas[`${name}Patch`] = stripTypebox(serviceSchemas.patch)
    if (serviceSchemas.query) schemas[`${name}Query`] = stripTypebox(serviceSchemas.query)

    Object.assign(paths, buildPaths(serviceSchemas, serviceName, refPrefix))
  }

  // Authentication endpoint
  paths['/authentication'] = {
    post: {
      tags: ['authentication'],
      summary: 'Authenticate',
      operationId: 'authenticate',
      requestBody: {
        required: true,
        content: {
          'application/json': {
            schema: {
              type: 'object',
              required: ['strategy'],
              properties: {
                strategy: { type: 'string', enum: ['local', 'jwt'] },
                email: { type: 'string', format: 'email' },
                password: { type: 'string' },
                accessToken: { type: 'string' },
              },
            },
          },
        },
      },
      responses: {
        '201': {
          description: 'Authenticated',
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: {
                  accessToken: { type: 'string' },
                  authentication: { type: 'object' },
                  user: { $ref: `${refPrefix}Users` },
                },
              },
            },
          },
        },
        '401': { description: 'Not authenticated' },
      },
    },
  }

  return {
    openapi: '3.1.0',
    info: {
      title: 'feathers-baas API',
      version: '0.0.1',
      description: 'Auto-generated from TypeBox schemas',
    },
    servers: [
      { url: `http://${config.host === '0.0.0.0' ? 'localhost' : config.host}:${config.port}` },
    ],
    paths,
    components: {
      schemas,
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
    },
    security: [{ bearerAuth: [] }],
  }
}

const SCALAR_HTML = `<!DOCTYPE html>
<html>
<head>
  <title>feathers-baas API Docs</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
  <script id="api-reference" data-url="/openapi.json"></script>
  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
</body>
</html>`

export function configureOpenApi(app: Application): void {
  const koaApp = app as unknown as {
    use(mw: (ctx: { path: string; status: number; body: unknown; type: string }, next: () => Promise<void>) => Promise<void>): void
  }

  koaApp.use(async (ctx, next) => {
    if (ctx.path === '/openapi.json') {
      ctx.status = 200
      ctx.type = 'application/json'
      ctx.body = generateOpenApiSpec(app)
      return
    }

    if (ctx.path === '/docs') {
      ctx.status = 200
      ctx.type = 'text/html'
      ctx.body = SCALAR_HTML
      return
    }

    await next()
  })
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function singularize(s: string): string {
  if (s.endsWith('s')) return s.slice(0, -1)
  return s
}
