// Generated by feathers-baas. Safe to edit.
import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { createRequire } from 'node:module'
import type { Application } from './declarations.js'
import { logger } from './logger.js'

export interface PluginTemplates {
  [templateName: string]: string
}

export interface PluginGenerators {
  [generatorName: string]: (app: Application, options: Record<string, unknown>) => Promise<void>
}

export interface FeathersBaasPlugin {
  name: string
  version: string
  install(app: Application, options: Record<string, unknown>): Promise<void>
  getTemplates?(): PluginTemplates
  getGenerators?(): PluginGenerators
}

function isPlugin(obj: unknown): obj is FeathersBaasPlugin {
  if (!obj || typeof obj !== 'object') return false
  const p = obj as Record<string, unknown>
  return typeof p['name'] === 'string' &&
    typeof p['version'] === 'string' &&
    typeof p['install'] === 'function'
}

export function discoverPlugins(projectRoot?: string): string[] {
  const root = projectRoot ?? process.cwd()
  const pkgPath = join(root, 'package.json')

  if (!existsSync(pkgPath)) return []

  const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8')) as Record<string, unknown>
  const allDeps = {
    ...(pkg['dependencies'] as Record<string, string> | undefined),
  }

  const require = createRequire(join(root, 'node_modules'))
  const pluginNames: string[] = []

  for (const depName of Object.keys(allDeps)) {
    try {
      const depPkgPath = require.resolve(join(depName, 'package.json'))
      const depPkg = JSON.parse(readFileSync(depPkgPath, 'utf-8')) as Record<string, unknown>

      const hasKeyword = Array.isArray(depPkg['keywords']) &&
        (depPkg['keywords'] as string[]).includes('feathers-baas-plugin')
      const hasFlag = depPkg['feathers-baas-plugin'] === true

      if (hasKeyword || hasFlag) {
        pluginNames.push(depName)
      }
    } catch {
      // dependency not resolvable — skip
    }
  }

  return pluginNames
}

export async function loadPlugin(packageName: string): Promise<FeathersBaasPlugin> {
  const mod = await import(packageName) as Record<string, unknown>
  const plugin = mod['default'] ?? mod

  if (!isPlugin(plugin)) {
    throw new Error(
      `Package "${packageName}" does not export a valid FeathersBaasPlugin (needs name, version, install)`,
    )
  }

  return plugin
}

export async function installPlugins(
  app: Application,
  options?: { projectRoot?: string; pluginOptions?: Record<string, Record<string, unknown>> },
): Promise<FeathersBaasPlugin[]> {
  const pluginNames = discoverPlugins(options?.projectRoot)

  if (pluginNames.length === 0) {
    logger.debug('No feathers-baas plugins discovered')
    return []
  }

  logger.info({ plugins: pluginNames }, `Discovered ${pluginNames.length} plugin(s)`)

  const installed: FeathersBaasPlugin[] = []

  for (const name of pluginNames) {
    try {
      const plugin = await loadPlugin(name)
      const opts = options?.pluginOptions?.[name] ?? {}
      await plugin.install(app, opts)
      installed.push(plugin)
      logger.info({ plugin: plugin.name, version: plugin.version }, 'Plugin installed')
    } catch (err) {
      logger.error({ err, plugin: name }, 'Failed to install plugin')
      throw err
    }
  }

  return installed
}
