// Generated by feathers-baas. Safe to edit.
import type { Application } from './declarations.js'
import { logger } from './logger.js'

const DEFAULT_ROLES = [
  {
    name: 'admin',
    permissions: [{ service: '*', methods: ['*'] }],
  },
  {
    name: 'user',
    permissions: [
      { service: 'users', methods: ['get', 'patch'] },
    ],
  },
]

export async function seedDatabase(app: Application): Promise<void> {
  const config = app.get('config')
  const rolesService = app.service('roles') as any
  const usersService = app.service('users') as any

  // 1. Seed default roles
  for (const role of DEFAULT_ROLES) {
    const existing = await rolesService._find({
      query: { name: role.name, $limit: 1 },
      paginate: { default: 1, max: 1 },
    })
    if (existing.total === 0 || existing.data?.length === 0) {
      const now = new Date().toISOString()
      await rolesService._create({ ...role, createdAt: now, updatedAt: now })
      logger.info(`Created role: ${role.name}`)
    } else {
      logger.info(`Role "${role.name}" already exists, skipping`)
    }
  }

  // 2. Seed admin user from ADMIN_EMAIL / ADMIN_PASSWORD
  if (config.adminEmail && config.adminPassword) {
    const existing = await usersService._find({
      query: { email: config.adminEmail, $limit: 1 },
      paginate: { default: 1, max: 1 },
    })
    if (existing.total === 0 || existing.data?.length === 0) {
      // Use the public create (no provider = internal) so password hashing
      // and verification hooks run, but preventAdminRole is skipped
      const admin = await usersService.create(
        {
          email: config.adminEmail,
          password: config.adminPassword,
          roles: ['admin'],
        },
      )
      // Force-verify the admin account (bypass hooks)
      const adminId = admin.id ?? admin._id
      await usersService._patch(adminId, { isVerified: true })
      logger.info(`Created admin user: ${config.adminEmail}`)
    } else {
      logger.info(`Admin user "${config.adminEmail}" already exists, skipping`)
    }
  } else {
    logger.warn('ADMIN_EMAIL / ADMIN_PASSWORD not set in .env — skipping admin user seed')
  }
}
