// Generated by feathers-baas. Safe to edit.
import type { Knex } from 'knex'
import * as argon2 from 'argon2'

const ROLES = [
  {
    name: 'admin',
    permissions: [
      { service: 'users', methods: ['*'] },
      { service: 'roles', methods: ['*'] },
    ],
  },
  {
    name: 'user',
    permissions: [
      { service: 'users', methods: ['get', 'patch'] },
    ],
  },
  {
    name: 'guest',
    permissions: [],
  },
]

export async function seed(knex: Knex): Promise<void> {
  // Upsert roles — idempotent
  for (const role of ROLES) {
    await knex('roles')
      .insert({
        name: role.name,
        permissions: JSON.stringify(role.permissions),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .onConflict('name')
      .merge({ permissions: JSON.stringify(role.permissions), updated_at: new Date().toISOString() })
  }

  // Seed bootstrap admin user if env vars are provided
  const email = process.env['ADMIN_EMAIL']
  const password = process.env['ADMIN_PASSWORD']

  if (!email || !password) {
    console.log('ADMIN_EMAIL / ADMIN_PASSWORD not set — skipping admin user seed')
    return
  }

  const passwordHash = await argon2.hash(password, {
    type: argon2.argon2id,
    memoryCost: 65536,
    timeCost: 3,
    parallelism: 4,
  })

  await knex('users')
    .insert({
      email,
      password: passwordHash,
      roles: ['admin'],
      is_verified: true,
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    })
    .onConflict('email')
    .ignore()

  console.log(`Admin user seeded: ${email}`)
}
