// Generated by feathers-baas. Safe to edit.
import { authenticate } from '@feathersjs/authentication'
import { BadRequest, NotFound } from '@feathersjs/errors'
import type { HookContext } from '@feathersjs/feathers'
import { processUpload } from './middleware.js'
import type { FilesConfigOptions } from './types.js'
import type { FileData } from './files.schema.js'

/**
 * before.create hook: parse multipart body, stream file to the configured
 * driver, and build the metadata record that the KnexService will persist.
 *
 * Expects `context.params.req` (the raw IncomingMessage) to be set — the
 * @feathersjs/koa rest transport exposes it via ctx.feathers.
 */
export function handleUpload(opts: FilesConfigOptions) {
  return async (context: HookContext): Promise<void> => {
    // The raw Node.js request is available via params when using the REST transport
    const req = context.params['req'] as import('node:http').IncomingMessage | undefined
    if (!req) {
      // Internal call (e.g. from a seed) — data must already be pre-populated
      return
    }

    const result = await processUpload(req, opts.driver, opts)

    const userId = (context.params['user'] as Record<string, unknown> | undefined)?.['id']

    const data: FileData = {
      key: result.key,
      bucket: result.bucket,
      driver: result.driverType as FileData['driver'],
      mimeType: result.mimeType,
      size: result.size,
      originalName: result.originalName,
      uploadedBy: typeof userId === 'string' ? userId : undefined,
      metadata: {},
    }

    context.data = data
  }
}

/**
 * before.remove hook: delete the binary from the driver before removing
 * the metadata row. Uses the internal _get to avoid re-running hooks.
 */
export function deleteFromDriver(opts: FilesConfigOptions) {
  return async (context: HookContext): Promise<void> => {
    const id = context.id
    if (!id) throw new BadRequest('id is required for remove')

    const service = context.service as { _get(id: unknown): Promise<unknown> }
    const record = await service._get(id)

    if (!record || typeof record !== 'object') {
      throw new NotFound(`File ${String(id)} not found`)
    }

    const key = (record as Record<string, unknown>)['key'] as string
    await opts.driver.delete(key)
  }
}

export const filesHooks = (opts: FilesConfigOptions) => ({
  around: {
    all: [],
    find: [authenticate('jwt')],
    get: [authenticate('jwt')],
    create: [],       // upload endpoint uses its own auth flow (see service)
    update: [authenticate('jwt')],
    patch: [authenticate('jwt')],
    remove: [authenticate('jwt')],
  },
  before: {
    all: [],
    find: [],
    get: [],
    create: [authenticate('jwt'), handleUpload(opts)],
    update: [],
    patch: [],
    remove: [deleteFromDriver(opts)],
  },
  after: {
    all: [],
  },
  error: {},
})
