// Generated by feathers-baas. Safe to edit.
import type { Knex } from 'knex'
import { FilesClass } from './files.class.js'
import { filesHooks } from './files.hooks.js'
import { fileRecordSchema, fileDataSchema, filePatchSchema, fileQuerySchema } from './files.schema.js'
import type { FilesConfigOptions } from './types.js'

/**
 * Register the files service on the Feathers app.
 *
 * Call this in your app bootstrap AFTER the Knex database configurator and
 * AFTER the authentication configurator, because the files hooks use authenticate().
 *
 * @example
 * ```ts
 * import { configureFiles, LocalDriver } from '@feathers-baas/plugin-files'
 *
 * configureFiles(app, {
 *   driver: new LocalDriver({ directory: './uploads', jwtSecret: config.jwtSecret, baseUrl: 'http://localhost:3030' }),
 *   driverType: 'local',
 *   bucket: 'uploads',
 * })
 * ```
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function configureFiles(app: any, opts: FilesConfigOptions): void {
  const knex = app.get('knex') as Knex

  app.use(
    'files',
    new FilesClass({
      Model: knex,
      name: 'files',
      paginate: { default: 50, max: 200 },
    }),
    {
      methods: ['find', 'get', 'create', 'patch', 'remove'],
      events: [],
    },
  )

  app.service('files').hooks(filesHooks(opts))

  // Register schemas with the OpenAPI registry if feathers-baas/core has set it up.
  // We read from the app rather than importing core directly to avoid a hard dependency.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const registerSchemas = app.get('registerServiceSchemas') as ((name: string, schemas: any) => void) | undefined
  if (typeof registerSchemas === 'function') {
    registerSchemas('files', {
      main: fileRecordSchema,
      data: fileDataSchema,
      patch: filePatchSchema,
      query: fileQuerySchema,
      methods: ['find', 'get', 'create', 'patch', 'remove'],
      // Override the auto-generated POST /files with a multipart/form-data operation
      customPaths: {
        '/files': {
          post: {
            tags: ['files'],
            summary: 'Upload a file',
            operationId: 'uploadFile',
            requestBody: {
              required: true,
              content: {
                'multipart/form-data': {
                  schema: {
                    type: 'object',
                    required: ['file'],
                    properties: {
                      file: {
                        type: 'string',
                        format: 'binary',
                        description: 'The file to upload',
                      },
                    },
                  },
                },
              },
            },
            responses: {
              '201': {
                description: 'File uploaded and metadata stored',
                content: {
                  'application/json': {
                    schema: { $ref: '#/components/schemas/Files' },
                  },
                },
              },
              '400': { description: 'No file attached or unsupported MIME type' },
              '401': { description: 'Not authenticated' },
              '413': { description: 'File exceeds maximum size' },
            },
          },
        },
      },
    })
  }
}
