// Generated by feathers-baas. Safe to edit.
import { Type, type Static, querySyntax } from '@feathersjs/typebox'

// Full DB row for a stored file
export const fileRecordSchema = Type.Object(
  {
    id: Type.String({ format: 'uuid' }),
    key: Type.String({ description: 'Storage key / path within the bucket' }),
    bucket: Type.String(),
    driver: Type.Union([
      Type.Literal('local'),
      Type.Literal('s3'),
      Type.Literal('gcs'),
    ]),
    mimeType: Type.String(),
    size: Type.Number({ description: 'File size in bytes' }),
    originalName: Type.String(),
    uploadedBy: Type.Optional(Type.String({ format: 'uuid' })),
    metadata: Type.Record(Type.String(), Type.Unknown(), {
      description: 'Arbitrary key-value metadata stored as JSONB',
    }),
    createdAt: Type.String({ format: 'date-time' }),
  },
  { $id: 'FileRecord', additionalProperties: false },
)

export type FileRecord = Static<typeof fileRecordSchema>

// Data written to DB after a successful upload
export const fileDataSchema = Type.Object(
  {
    key: Type.String(),
    bucket: Type.String(),
    driver: Type.Union([
      Type.Literal('local'),
      Type.Literal('s3'),
      Type.Literal('gcs'),
    ]),
    mimeType: Type.String(),
    size: Type.Number(),
    originalName: Type.String(),
    uploadedBy: Type.Optional(Type.String()),
    metadata: Type.Optional(Type.Record(Type.String(), Type.Unknown())),
  },
  { $id: 'FileData', additionalProperties: false },
)

export type FileData = Static<typeof fileDataSchema>

// Patchable fields — only metadata can be updated post-upload
export const filePatchSchema = Type.Object(
  {
    metadata: Type.Optional(Type.Record(Type.String(), Type.Unknown())),
  },
  { $id: 'FilePatch', additionalProperties: false },
)

export type FilePatch = Static<typeof filePatchSchema>

// Query parameters
export const fileQuerySchema = querySyntax(
  Type.Object({
    id: Type.Optional(Type.String()),
    key: Type.Optional(Type.String()),
    driver: Type.Optional(Type.String()),
    bucket: Type.Optional(Type.String()),
    uploadedBy: Type.Optional(Type.String()),
    mimeType: Type.Optional(Type.String()),
  }),
  {},
  { $id: 'FileQuery', additionalProperties: false },
)

export type FileQuery = Static<typeof fileQuerySchema>
