// Generated by feathers-baas. Safe to edit.
import { KnexService } from '@feathersjs/knex'
import type { KnexAdapterParams, KnexAdapterOptions } from '@feathersjs/knex'
import type { FileRecord, FileData, FilePatch, FileQuery } from './files.schema.js'

export type FilesParams = KnexAdapterParams<FileQuery>

/**
 * KnexService subclass for the files metadata table.
 * Actual binary storage is handled by the configured FileDriver;
 * this class only manages the metadata row in the database.
 */
export class FilesClass extends KnexService<FileRecord, FileData, FilesParams, FilePatch> {
  constructor(options: KnexAdapterOptions) {
    super(options)
  }
}
