// Generated by feathers-baas. Safe to edit.
import type { Knex } from 'knex'
import { FilesClass } from './files.class.js'
import { filesHooks } from './files.hooks.js'
import type { FilesConfigOptions } from './types.js'

/**
 * Register the files service on the Feathers app.
 *
 * Call this in your app bootstrap AFTER the Knex database configurator and
 * AFTER the authentication configurator, because the files hooks use authenticate().
 *
 * @example
 * ```ts
 * import { configureFiles, LocalDriver } from '@feathers-baas/plugin-files'
 *
 * configureFiles(app, {
 *   driver: new LocalDriver({ directory: './uploads', jwtSecret: config.jwtSecret, baseUrl: 'http://localhost:3030' }),
 *   driverType: 'local',
 *   bucket: 'uploads',
 * })
 * ```
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function configureFiles(app: any, opts: FilesConfigOptions): void {
  const knex = app.get('knex') as Knex

  app.use(
    'files',
    new FilesClass({
      Model: knex,
      name: 'files',
      paginate: { default: 50, max: 200 },
    }),
    {
      methods: ['find', 'get', 'create', 'patch', 'remove'],
      events: [],
    },
  )

  app.service('files').hooks(filesHooks(opts))
}
