// Generated by feathers-baas. Safe to edit.
export { configureFiles } from './files.service.js'
export { FilesClass } from './files.class.js'
export { filesHooks } from './files.hooks.js'
export { processUpload } from './middleware.js'

// Drivers
export { LocalDriver } from './drivers/local.driver.js'
export type { LocalDriverOptions } from './drivers/local.driver.js'
export { S3Driver } from './drivers/s3.driver.js'
export type { S3DriverOptions } from './drivers/s3.driver.js'
export { GCSDriver } from './drivers/gcs.driver.js'
export type { GCSDriverOptions } from './drivers/gcs.driver.js'

// Types
export type {
  FileDriver,
  FileMeta,
  PutResult,
  FileListEntry,
  FilesConfigOptions,
  DriverType,
  UploadResult,
} from './types.js'

// Schema
export type { FileRecord, FileData, FilePatch, FileQuery } from './files.schema.js'
export {
  fileRecordSchema,
  fileDataSchema,
  filePatchSchema,
  fileQuerySchema,
} from './files.schema.js'
