// Generated by feathers-baas. Safe to edit.
import { createRequire } from 'node:module'
import type { FeathersBaasPlugin } from './plugin.js'

const pkg = createRequire(import.meta.url)('../package.json') as { version: string }

const plugin: FeathersBaasPlugin = {
  name: '@feathers-baas/plugin-files',
  version: pkg.version,
  async install(_app, _options) {
    // Files plugin requires explicit driver configuration — users call
    // configureFiles(app, opts) manually in their service setup.
    // Auto-install is a no-op; discovery confirms the plugin is present.
  },
}

export default plugin

export { configureFiles } from './files.service.js'
export { FilesClass } from './files.class.js'
export { filesHooks } from './files.hooks.js'
export { processUpload } from './middleware.js'

// Drivers
export { LocalDriver } from './drivers/local.driver.js'
export type { LocalDriverOptions } from './drivers/local.driver.js'
export { S3Driver } from './drivers/s3.driver.js'
export type { S3DriverOptions } from './drivers/s3.driver.js'
export { GCSDriver } from './drivers/gcs.driver.js'
export type { GCSDriverOptions } from './drivers/gcs.driver.js'

// Types
export type {
  FileDriver,
  FileMeta,
  PutResult,
  FileListEntry,
  FilesConfigOptions,
  DriverType,
  UploadResult,
} from './types.js'

// Schema
export type { FileRecord, FileData, FilePatch, FileQuery } from './files.schema.js'
export {
  fileRecordSchema,
  fileDataSchema,
  filePatchSchema,
  fileQuerySchema,
} from './files.schema.js'
