// Generated by feathers-baas. Safe to edit.
import busboy from 'busboy'
import { randomUUID } from 'node:crypto'
import { extname } from 'node:path'
import { PassThrough } from 'node:stream'
import { BadRequest } from '@feathersjs/errors'
import type { IncomingMessage } from 'node:http'
import type { FileDriver, FileMeta, FilesConfigOptions, UploadResult } from './types.js'

/**
 * Parse a multipart/form-data request and stream the first file field
 * directly to the configured FileDriver.
 *
 * Returns structured metadata once the upload completes; throws BadRequest
 * for validation failures (MIME type, file size).
 *
 * Usage: call this from a Koa middleware or Feathers hook before the
 * service's create path runs.
 */
export async function processUpload(
  req: IncomingMessage,
  driver: FileDriver,
  opts: Pick<FilesConfigOptions, 'bucket' | 'driverType' | 'maxFileSize' | 'allowedMimeTypes'>,
): Promise<UploadResult> {
  const maxFileSize = opts.maxFileSize ?? 52_428_800 // 50 MB default

  return new Promise((resolve, reject) => {
    let bb: ReturnType<typeof busboy>

    try {
      bb = busboy({
        headers: req.headers as Record<string, string | string[]>,
        limits: { files: 1, fileSize: maxFileSize },
      })
    } catch (err) {
      reject(new BadRequest('Invalid multipart request'))
      return
    }

    let settled = false
    let bytesWritten = 0

    const settle = (val: UploadResult | Error): void => {
      if (settled) return
      settled = true
      if (val instanceof Error) {
        reject(val)
      } else {
        resolve(val)
      }
    }

    bb.on('file', (fieldname, fileStream, info) => {
      const { filename, mimeType } = info

      if (opts.allowedMimeTypes && opts.allowedMimeTypes.length > 0) {
        if (!opts.allowedMimeTypes.includes(mimeType)) {
          fileStream.resume() // drain to avoid hanging
          settle(new BadRequest(`MIME type ${mimeType} is not allowed`))
          return
        }
      }

      // Build a collision-safe key: uuid + original extension
      const ext = extname(filename)
      const key = `${randomUUID()}${ext}`

      const meta: FileMeta = {
        mimeType,
        originalName: filename,
        size: undefined, // actual size determined after streaming
      }

      // Track bytes for the size field
      const pass = new PassThrough()
      pass.on('data', (chunk: Buffer) => {
        bytesWritten += chunk.length
      })
      fileStream.pipe(pass)

      driver
        .put(key, pass, meta)
        .then((result) => {
          settle({
            key: result.key,
            size: result.size > 0 ? result.size : bytesWritten,
            mimeType,
            originalName: filename,
            bucket: opts.bucket,
            driverType: opts.driverType,
          })
        })
        .catch((err: unknown) => {
          settle(err instanceof Error ? err : new Error(String(err)))
        })

      fileStream.on('limit', () => {
        settle(new BadRequest(`File exceeds the maximum allowed size of ${maxFileSize} bytes`))
      })
    })

    bb.on('error', (err) => {
      settle(err instanceof Error ? err : new Error(String(err)))
    })

    bb.on('finish', () => {
      // 'finish' fires when the busboy form is fully parsed but the async
      // driver.put may still be in flight — the promise handles that.
    })

    req.pipe(bb)
  })
}
