// Generated by feathers-baas. Safe to edit.
import type { Readable } from 'node:stream'

/** Metadata provided by the caller when uploading a file. */
export interface FileMeta {
  mimeType: string
  size?: number
  originalName: string
  uploadedBy?: string
  metadata?: Record<string, unknown>
}

/** Result of a driver put operation. */
export interface PutResult {
  key: string
  size: number
}

/** A listing entry returned by driver.list(). */
export interface FileListEntry {
  key: string
  size: number
  lastModified: Date
}

/**
 * Uniform interface implemented by every storage driver.
 * All drivers must support streaming — never buffer entire files in memory.
 */
export interface FileDriver {
  /** Upload a file stream, return key + actual size. */
  put(key: string, stream: Readable, meta: FileMeta): Promise<PutResult>
  /** Open a read stream for the given key. */
  get(key: string): Promise<Readable>
  /** Permanently delete a stored file. */
  delete(key: string): Promise<void>
  /**
   * Generate a time-limited URL granting read access.
   * @param expiresIn seconds until the URL expires
   */
  signUrl(key: string, expiresIn: number): Promise<string>
  /** List objects under a key prefix. */
  list(prefix: string): Promise<FileListEntry[]>
}

/** Which driver is active — stored on each FileRecord for provenance. */
export type DriverType = 'local' | 's3' | 'gcs'

/** Structured result returned after a successful upload pipeline. */
export interface UploadResult {
  key: string
  size: number
  mimeType: string
  originalName: string
  bucket: string
  driverType: string
}

/** Options bag passed to configureFiles(). */
export interface FilesConfigOptions {
  /** Instantiated driver to use for all storage operations. */
  driver: FileDriver
  /** Logical name of the driver (stored in DB). */
  driverType: DriverType
  /** Bucket / top-level prefix for this deployment. */
  bucket: string
  /** Maximum allowed file size in bytes. Default: 52_428_800 (50 MB). */
  maxFileSize?: number
  /** Allowed MIME types. If empty/undefined, all types are accepted. */
  allowedMimeTypes?: string[]
}
