// Generated by feathers-baas. Safe to edit.
import authManagement from 'feathers-authentication-management'
import type { Application } from '../declarations.js'
import { createNotifier } from './notifier.js'

/**
 * Configure feathers-authentication-management on the app.
 *
 * Must be called AFTER configureAuth() and configureServices() since it
 * depends on the 'users' service and the auth strategies existing.
 *
 * Registers the 'authManagement' service which handles:
 * - Email verification (verify tokens on user creation)
 * - Password reset (send/reset flows)
 * - Password change
 * - Identity (email) change
 *
 * The notifier function delegates to the BullMQ-backed notification queue
 * when REDIS_URL is configured, or falls back to console logging.
 */
export function configureAuthManagement(app: Application): void {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ;(app as any).configure(authManagement({
    service: 'users',
    notifier: createNotifier(app),
    // Skip verification check for password reset — allows resetting
    // even if the user hasn't verified their email yet
    skipIsVerifiedCheck: false,
  }))
}
