// Generated by feathers-baas. Safe to edit.
import { AuthenticationService } from '@feathersjs/authentication'
import type { Params } from '@feathersjs/feathers'
import type { Application } from '../declarations.js'
import { ArgonLocalStrategy } from './strategies/local.strategy.js'
import { BaasJWTStrategy } from './strategies/jwt.strategy.js'

interface KoaCookieJar {
  set(name: string, value: string | null, options?: Record<string, unknown>): void
}

function parseExpiryMs(expiry: string): number {
  const units: Record<string, number> = { s: 1000, m: 60_000, h: 3_600_000, d: 86_400_000 }
  const m = expiry.match(/^(\d+)([smhd])$/)
  return m ? parseInt(m[1]!) * (units[m[2]!] ?? 86_400_000) : 7 * 86_400_000
}

function refreshCookieOptions(maxAge: number) {
  return {
    httpOnly: true,
    secure: process.env['NODE_ENV'] === 'production',
    sameSite: 'lax',
    path: '/authentication',
    maxAge,
  }
}

class BaasAuthenticationService extends AuthenticationService {
  override async create(data: Record<string, unknown>, params?: Params) {
    const result = (await super.create(data, params)) as Record<string, unknown>

    // Only issue a refresh token for password-based logins, not JWT re-auths
    if (data['strategy'] === 'local') {
      const config = (this.app as Application).get('config')
      const user = result['user'] as Record<string, unknown> | undefined
      const userId = user?.['id'] ?? user?.['_id']

      if (userId) {
        const refreshToken = await this.createAccessToken(
          { sub: String(userId) },
          { header: { alg: 'HS256', typ: 'refresh' }, expiresIn: config.jwtRefreshExpiry },
        )

        // Return refresh token in body for non-browser / API clients
        result['refreshToken'] = refreshToken

        // Set HTTP-only cookie for browser clients using @feathersjs/authentication-client
        // The BaasJWTStrategy reads this cookie to transparently refresh expired access tokens
        const cookies = (params?.connection as { cookies?: KoaCookieJar } | undefined)?.cookies
        cookies?.set('feathers-refresh', refreshToken, refreshCookieOptions(parseExpiryMs(config.jwtRefreshExpiry)))
      }
    }

    return result
  }

  override async remove(id: string | null, params?: Params) {
    const result = await super.remove(id, params)
    const cookies = (params?.connection as { cookies?: KoaCookieJar } | undefined)?.cookies
    cookies?.set('feathers-refresh', null, refreshCookieOptions(0))
    return result
  }
}

export function configureAuth(app: Application): void {
  const config = app.get('config')

  // Must be set BEFORE registering strategies — verifyConfiguration() reads it at register time
  const isMongo = !!app.get('mongoDb')

  app.set('authentication', {
    secret: config.jwtSecret,
    entity: 'user',
    entityId: isMongo ? '_id' : 'id',
    service: 'users',
    authStrategies: ['jwt', 'local'],
    jwtOptions: {
      header: { alg: 'HS256', typ: 'access' },
      audience: 'https://feathers-baas.app',
      issuer: 'feathers-baas',
      algorithm: 'HS256',
      expiresIn: config.jwtExpiry,
    },
    local: {
      usernameField: 'email',
      passwordField: 'password',
    },
  })

  const authService = new BaasAuthenticationService(app)
  authService.register('jwt', new BaasJWTStrategy())
  authService.register('local', new ArgonLocalStrategy())

  app.use('authentication', authService)
}
