// Generated by feathers-baas. Safe to edit.
import { AuthenticationService, JWTStrategy } from '@feathersjs/authentication'
import type { Params } from '@feathersjs/feathers'
import type { Application } from '../declarations.js'
import { ArgonLocalStrategy } from './strategies/local.strategy.js'

class BaasAuthenticationService extends AuthenticationService {
  override async create(data: Record<string, unknown>, params?: Params) {
    const result = (await super.create(data, params)) as Record<string, unknown>

    // Only issue a refresh token for password-based logins, not JWT re-auths
    if (data['strategy'] === 'local') {
      const config = (this.app as Application).get('config')
      const user = result['user'] as Record<string, unknown> | undefined
      const userId = user?.['id'] ?? user?.['_id']

      if (userId) {
        const refreshToken = await this.createAccessToken(
          { sub: String(userId) },
          { header: { alg: 'HS256', typ: 'refresh' }, expiresIn: config.jwtRefreshExpiry },
        )
        result['refreshToken'] = refreshToken
      }
    }

    return result
  }
}

export function configureAuth(app: Application): void {
  const config = app.get('config')

  // Must be set BEFORE registering strategies — verifyConfiguration() reads it at register time
  const isMongo = !!app.get('mongoDb')

  app.set('authentication', {
    secret: config.jwtSecret,
    entity: 'user',
    entityId: isMongo ? '_id' : 'id',
    service: 'users',
    authStrategies: ['jwt', 'local'],
    jwtOptions: {
      header: { type: 'access' },
      audience: 'https://feathers-baas.app',
      issuer: 'feathers-baas',
      algorithm: 'HS256',
      expiresIn: config.jwtExpiry,
    },
    local: {
      usernameField: 'email',
      passwordField: 'password',
    },
  })

  const authService = new BaasAuthenticationService(app)
  authService.register('jwt', new JWTStrategy())
  authService.register('local', new ArgonLocalStrategy())

  app.use('authentication', authService)
}
