// Generated by feathers-baas. Safe to edit.
import { AuthenticationService, JWTStrategy } from '@feathersjs/authentication'
import type { Application } from '../declarations.js'
import { ArgonLocalStrategy } from './strategies/local.strategy.js'

export function configureAuth(app: Application): void {
  const config = app.get('config')

  // Must be set BEFORE registering strategies — verifyConfiguration() reads it at register time
  app.set('authentication', {
    secret: config.jwtSecret,
    entity: 'user',
    entityId: 'id',
    service: 'users',
    authStrategies: ['jwt', 'local'],
    jwtOptions: {
      header: { type: 'access' },
      audience: 'https://feathers-baas.app',
      issuer: 'feathers-baas',
      algorithm: 'HS256',
      expiresIn: config.jwtExpiry,
    },
    local: {
      usernameField: 'email',
      passwordField: 'password',
    },
  })

  const authService = new AuthenticationService(app)
  authService.register('jwt', new JWTStrategy())
  authService.register('local', new ArgonLocalStrategy())

  app.use('authentication', authService)
}
