// Generated by feathers-baas. Safe to edit.
// This notifier is a stub used by feathers-authentication-management.
// Replace in M2 with a real BullMQ-backed implementation.
import type { Application } from '../declarations.js'
import { logger } from '../logger.js'

export type NotificationType =
  | 'resendVerifySignup'
  | 'verifySignup'
  | 'verifySignupSetPassword'
  | 'sendResetPwd'
  | 'resetPwd'
  | 'passwordChange'
  | 'identityChange'

export type NotifierFn = (
  type: NotificationType,
  user: Record<string, unknown>,
  notifierOptions: Record<string, unknown>,
) => Promise<void>

export function createNotifier(_app: Application): NotifierFn {
  return async (type, user, _opts) => {
    // Stub: log notification intent — wire real drivers in M2
    logger.info({ type, userId: user['id'], email: user['email'] }, 'Notification triggered')
  }
}
