// Generated by feathers-baas. Safe to edit.
// This notifier delegates to app.get('notifier') when set — wire the real
// BullMQ implementation by calling app.set('notifier', createBullMQNotifier(...))
// from @feathers-baas/plugin-notifications during app bootstrap.
// Falls back to console-logging when no notifier is configured.
import type { Application, AppNotifierFn } from '../declarations.js'
import { logger } from '../logger.js'

export type NotificationType =
  | 'resendVerifySignup'
  | 'verifySignup'
  | 'verifySignupSetPassword'
  | 'sendResetPwd'
  | 'resetPwd'
  | 'passwordChange'
  | 'identityChange'

export type { AppNotifierFn as NotifierFn }

export function createNotifier(app: Application): AppNotifierFn {
  return async (type, user, opts) => {
    const delegate = app.get('notifier')
    if (delegate) {
      return delegate(type, user, opts)
    }
    // Sync fallback — logs intent when no notification plugin is configured
    logger.info(
      { type, userId: user['id'], email: user['email'] },
      'Notification triggered (no driver configured — install @feathers-baas/plugin-notifications)',
    )
  }
}
