// Generated by feathers-baas. Safe to edit.
export { DriverRegistry } from './registry.js'
export { createBullMQNotifier } from './notifier.js'
export type { NotifierFn, BullMQNotifierOptions } from './notifier.js'

// Queue
export { createNotificationQueue, enqueueNotification, NOTIFICATION_QUEUE_NAME } from './queue/producer.js'
export { createNotificationWorker } from './queue/worker.js'
export type { WorkerOptions } from './queue/worker.js'

// Drivers
export { SMTPDriver } from './drivers/smtp.driver.js'
export type { SMTPDriverOptions } from './drivers/smtp.driver.js'
export { ResendDriver } from './drivers/resend.driver.js'
export type { ResendDriverOptions } from './drivers/resend.driver.js'

// Types
export type {
  Notification,
  NotifierDriver,
  NotificationJob,
  NotificationEvent,
  AuthNotificationEvent,
} from './types.js'
