// Generated by feathers-baas. Safe to edit.
import { createRequire } from 'node:module'
import type { FeathersBaasPlugin } from './plugin.js'

const pkg = createRequire(import.meta.url)('../package.json') as { version: string }

const plugin: FeathersBaasPlugin = {
  name: '@feathers-baas/plugin-notifications',
  version: pkg.version,
  async install(_app, _options) {
    // Notification drivers are configured via core's configureNotifications()
    // based on env vars. Auto-install is a no-op; discovery confirms the plugin is present.
  },
}

export default plugin

export { DriverRegistry } from './registry.js'
export { createBullMQNotifier, createDirectNotifier } from './notifier.js'
export type { NotifierFn, BullMQNotifierOptions, DirectNotifierOptions } from './notifier.js'

// Queue
export { createNotificationQueue, enqueueNotification, NOTIFICATION_QUEUE_NAME } from './queue/producer.js'
export { createNotificationWorker } from './queue/worker.js'
export type { WorkerOptions } from './queue/worker.js'

// Drivers
export { SMTPDriver } from './drivers/smtp.driver.js'
export type { SMTPDriverOptions } from './drivers/smtp.driver.js'
export { ResendDriver } from './drivers/resend.driver.js'
export type { ResendDriverOptions } from './drivers/resend.driver.js'
export { SendGridDriver } from './drivers/sendgrid.driver.js'
export type { SendGridDriverOptions } from './drivers/sendgrid.driver.js'
export { BrevoDriver } from './drivers/brevo.driver.js'
export type { BrevoDriverOptions } from './drivers/brevo.driver.js'

// Types
export type {
  Notification,
  NotifierDriver,
  NotificationJob,
  NotificationEvent,
  AuthNotificationEvent,
} from './types.js'
