// Generated by feathers-baas. Safe to edit.
import type { Queue } from 'bullmq'
import type { NotificationJob, Notification, AuthNotificationEvent } from './types.js'
import { enqueueNotification } from './queue/producer.js'
import type { DriverRegistry } from './registry.js'

/**
 * Auth-management notification types mapped to feathers-baas event keys.
 * feathers-authentication-management passes these type strings to the notifier.
 */
const AUTH_MANAGEMENT_EVENT_MAP: Record<string, AuthNotificationEvent> = {
  resendVerifySignup: 'auth.resend-verify-signup',
  verifySignup: 'auth.verify-signup',
  verifySignupSetPassword: 'auth.verify-signup-set-password',
  sendResetPwd: 'auth.send-reset-pwd',
  resetPwd: 'auth.reset-pwd',
  passwordChange: 'auth.password-change',
  identityChange: 'auth.identity-change',
}

/**
 * Build a default Notification payload for each auth event type.
 * Templates use EJS — `<%= variable %>` for output, `<% code %>` for logic.
 */
function buildAuthNotification(
  type: AuthNotificationEvent,
  user: Record<string, unknown>,
  appUrl: string,
): Notification | null {
  const email = user['email'] as string
  if (!email) return null

  switch (type) {
    case 'auth.verify-signup':
    case 'auth.resend-verify-signup': {
      const token = user['verifyToken'] as string | undefined
      const verifyUrl = `${appUrl}/verify?token=${token ?? ''}`
      return {
        to: email,
        channel: 'email',
        subject: 'Verify your email address',
        bodyTemplate: `
          <h2>Welcome!</h2>
          <p>Click the link below to verify your email address:</p>
          <p><a href="<%= verifyUrl %>">Verify email</a></p>
          <p>This link expires in 24 hours.</p>
        `,
        textTemplate: `Verify your email: <%= verifyUrl %>`,
        data: { verifyUrl, user },
      }
    }

    case 'auth.send-reset-pwd': {
      const token = user['resetToken'] as string | undefined
      const resetUrl = `${appUrl}/reset-password?token=${token ?? ''}`
      return {
        to: email,
        channel: 'email',
        subject: 'Reset your password',
        bodyTemplate: `
          <h2>Password reset requested</h2>
          <p>Click the link below to reset your password:</p>
          <p><a href="<%= resetUrl %>">Reset password</a></p>
          <p>This link expires in 2 hours. If you did not request this, ignore this email.</p>
        `,
        textTemplate: `Reset your password: <%= resetUrl %>`,
        data: { resetUrl, user },
      }
    }

    case 'auth.reset-pwd': {
      return {
        to: email,
        channel: 'email',
        subject: 'Your password has been reset',
        bodyTemplate: `<p>Your password has been successfully reset. If you did not do this, please contact support immediately.</p>`,
        textTemplate: `Your password has been reset. If you did not do this, please contact support.`,
        data: { user },
      }
    }

    case 'auth.password-change': {
      return {
        to: email,
        channel: 'email',
        subject: 'Your password has been changed',
        bodyTemplate: `<p>Your account password was just changed. If this was not you, please contact support immediately.</p>`,
        textTemplate: `Your password was changed. Contact support if this wasn't you.`,
        data: { user },
      }
    }

    case 'auth.identity-change': {
      return {
        to: email,
        channel: 'email',
        subject: 'Your email address is being changed',
        bodyTemplate: `<p>A request was made to change your email address. Click the link to confirm.</p>`,
        textTemplate: `Confirm your email change by clicking the link in the HTML email.`,
        data: { user },
      }
    }

    case 'auth.verify-signup-set-password': {
      const token = user['verifyToken'] as string | undefined
      const verifyUrl = `${appUrl}/verify-set-password?token=${token ?? ''}`
      return {
        to: email,
        channel: 'email',
        subject: 'Set your password',
        bodyTemplate: `
          <h2>Set your password</h2>
          <p><a href="<%= verifyUrl %>">Set password</a></p>
        `,
        textTemplate: `Set your password: <%= verifyUrl %>`,
        data: { verifyUrl, user },
      }
    }
  }
}

export type NotifierFn = (
  type: string,
  user: Record<string, unknown>,
  notifierOptions: Record<string, unknown>,
) => Promise<void>

export interface BullMQNotifierOptions {
  /** BullMQ Queue instance — from createNotificationQueue(). */
  queue: Queue<NotificationJob>
  /** Driver registry — used to determine which drivers handle each event. */
  registry: DriverRegistry
  /**
   * Public base URL of the app, e.g. https://api.example.com
   * Used to construct verification / reset URLs in email templates.
   */
  appUrl: string
}

/**
 * Create a notifier function compatible with feathers-authentication-management.
 *
 * When an auth event fires (verifySignup, sendResetPwd, etc.), this notifier:
 * 1. Maps the event type to a feathers-baas notification event key
 * 2. Looks up all registered drivers for that event
 * 3. Enqueues one BullMQ job per driver
 * 4. Returns immediately — delivery is asynchronous
 *
 * Wire into the app:
 * ```ts
 * app.set('notifier', createBullMQNotifier({ queue, registry, appUrl }))
 * ```
 */
export function createBullMQNotifier(opts: BullMQNotifierOptions): NotifierFn {
  return async (type, user, _notifierOptions) => {
    const eventKey = AUTH_MANAGEMENT_EVENT_MAP[type]
    if (!eventKey) return // Unknown event type — no-op

    const notification = buildAuthNotification(eventKey, user, opts.appUrl)
    if (!notification) return // Missing required user fields — no-op

    const driverNames = opts.registry.getDriversForEvent(eventKey)
    if (driverNames.length === 0) return // No drivers configured for this event

    await Promise.all(
      driverNames.map((driverName) =>
        enqueueNotification(opts.queue, { driverName, notification }),
      ),
    )
  }
}
