// Generated by feathers-baas. Safe to edit.
import type { NotifierDriver, NotificationEvent } from './types.js'

/**
 * DriverRegistry maps event keys to the list of drivers that should handle
 * that event.
 *
 * A single driver instance can handle multiple events (e.g. the SMTP driver
 * handles all auth.* email events).
 *
 * @example
 * ```ts
 * const registry = new DriverRegistry()
 * registry.registerDriver(smtpDriver)
 * registry.mapEvent('auth.verify-signup', 'smtp')
 * registry.mapEvent('auth.send-reset-pwd', 'smtp')
 * ```
 */
export class DriverRegistry {
  private readonly drivers = new Map<string, NotifierDriver>()
  private readonly eventMap = new Map<NotificationEvent, string[]>()

  /** Register a driver under its name. Overwrites any existing driver with the same name. */
  registerDriver(driver: NotifierDriver): void {
    this.drivers.set(driver.name, driver)
  }

  /** Map a notification event to a driver name. Multiple calls for the same event add drivers. */
  mapEvent(event: NotificationEvent, driverName: string): void {
    const existing = this.eventMap.get(event) ?? []
    if (!existing.includes(driverName)) {
      existing.push(driverName)
    }
    this.eventMap.set(event, existing)
  }

  /** Look up a driver by name. Returns undefined if not registered. */
  getDriver(name: string): NotifierDriver | undefined {
    return this.drivers.get(name)
  }

  /** Get all driver names mapped to the given event. */
  getDriversForEvent(event: NotificationEvent): string[] {
    return this.eventMap.get(event) ?? []
  }

  /** All registered driver names. */
  listDriverNames(): string[] {
    return [...this.drivers.keys()]
  }
}
