// Generated by feathers-baas. Safe to edit.

/**
 * A single notification to be delivered to one recipient.
 * Templates are EJS strings — the worker renders them just before sending.
 */
export interface Notification {
  /** Recipient address — email address, phone number, device token, etc. */
  to: string
  /** Notification channel — determines which driver handles delivery. */
  channel: 'email' | 'sms' | 'push' | 'webhook'
  /** Email subject line (email channel only). */
  subject?: string
  /** EJS template string for the message body. */
  bodyTemplate: string
  /** Variables injected into the EJS template at render time. */
  data: Record<string, unknown>
  /** Optional plain-text fallback for HTML email. */
  textTemplate?: string
}

/**
 * A named notification driver — responsible for delivering one channel.
 * Drivers are registered in the DriverRegistry and looked up by name at
 * job processing time.
 */
export interface NotifierDriver {
  /** Unique name used as the registry key (e.g. 'smtp', 'resend'). */
  readonly name: string
  /** Deliver the notification to the recipient. */
  send(notification: Notification): Promise<void>
}

/**
 * Payload stored inside each BullMQ job.
 * Worker resolves driverName → NotifierDriver from the registry.
 */
export interface NotificationJob {
  driverName: string
  notification: Notification
}

/**
 * Maps auth-management event types to a human-readable event key used in
 * the notification event→driver registry.
 */
export type AuthNotificationEvent =
  | 'auth.resend-verify-signup'
  | 'auth.verify-signup'
  | 'auth.verify-signup-set-password'
  | 'auth.send-reset-pwd'
  | 'auth.reset-pwd'
  | 'auth.password-change'
  | 'auth.identity-change'

/** Union of all supported notification event keys. */
export type NotificationEvent = AuthNotificationEvent | string
