// Generated by feathers-baas. Safe to edit.
import type { Knex } from 'knex'
import 'dotenv/config'

function requireEnv(key: string): string {
  const v = process.env[key]
  if (!v) throw new Error(`Missing required environment variable: ${key}`)
  return v
}

const config: Record<string, Knex.Config> = {
  development: {
    client: 'pg',
    connection: requireEnv('DATABASE_URL'),
    migrations: { directory: './migrations', extension: 'ts' },
    seeds: { directory: './seeds', extension: 'ts' },
  },
  test: {
    client: 'pg',
    connection: process.env['TEST_DATABASE_URL'] ?? requireEnv('DATABASE_URL'),
    migrations: { directory: './migrations', extension: 'ts' },
    seeds: { directory: './seeds', extension: 'ts' },
  },
  production: {
    client: 'pg',
    connection: requireEnv('DATABASE_URL'),
    pool: { min: 2, max: 10 },
    migrations: { directory: './migrations', extension: 'ts' },
  },
}

export default config
