// Generated by feathers-baas. Safe to edit.
import { Type, type Static, querySyntax } from '@feathersjs/typebox'

// Full DB row — password is never returned to clients (stripped by after hooks)
export const userSchema = Type.Object(
  {
    id: Type.String({ format: 'uuid' }),
    email: Type.String({ format: 'email' }),
    password: Type.Optional(Type.String()),
    roles: Type.Array(Type.String()),
    isVerified: Type.Boolean(),
    isActive: Type.Boolean(),
    oauthIds: Type.Optional(Type.Record(Type.String(), Type.String())),
    // feathers-authentication-management fields
    verifyToken: Type.Optional(Type.String()),
    verifyShortToken: Type.Optional(Type.String()),
    verifyExpires: Type.Optional(Type.String({ format: 'date-time' })),
    verifyChanges: Type.Optional(Type.Record(Type.String(), Type.Unknown())),
    resetToken: Type.Optional(Type.String()),
    resetShortToken: Type.Optional(Type.String()),
    resetExpires: Type.Optional(Type.String({ format: 'date-time' })),
    resetAttempts: Type.Optional(Type.Number()),
    createdAt: Type.String({ format: 'date-time' }),
    updatedAt: Type.String({ format: 'date-time' }),
    deletedAt: Type.Optional(Type.String({ format: 'date-time' })),
  },
  { $id: 'User', additionalProperties: false },
)

export type User = Static<typeof userSchema>

// Input for create — password required, roles optional (defaults to ['user'])
export const userDataSchema = Type.Object(
  {
    email: Type.String({ format: 'email' }),
    password: Type.String({ minLength: 8 }),
    roles: Type.Optional(Type.Array(Type.String())),
  },
  { $id: 'UserData', additionalProperties: false },
)

export type UserData = Static<typeof userDataSchema>

// Input for patch — all fields optional
export const userPatchSchema = Type.Partial(
  Type.Object({
    email: Type.String({ format: 'email' }),
    password: Type.String({ minLength: 8 }),
    roles: Type.Array(Type.String()),
    isVerified: Type.Boolean(),
    isActive: Type.Boolean(),
  }),
  { $id: 'UserPatch', additionalProperties: false },
)

export type UserPatch = Static<typeof userPatchSchema>

// Query parameters — querySyntax adds $limit, $skip, $sort, $select, $and, $or
export const userQuerySchema = querySyntax(
  Type.Object({
    id: Type.Optional(Type.String()),
    email: Type.Optional(Type.String()),
    isVerified: Type.Optional(Type.Boolean()),
    isActive: Type.Optional(Type.Boolean()),
  }),
  {},
  { $id: 'UserQuery', additionalProperties: false },
)

export type UserQuery = Static<typeof userQuerySchema>
