// Generated by feathers-baas. Safe to edit.
import { KnexService } from '@feathersjs/knex'
import type { KnexAdapterParams, KnexAdapterOptions } from '@feathersjs/knex'
import type { Application } from '../../declarations.js'
import type { User, UserData, UserPatch, UserQuery } from './users.schema.js'

export type UsersParams = KnexAdapterParams<UserQuery>

export class UsersClass extends KnexService<User, UserData, UsersParams, UserPatch> {
  constructor(options: KnexAdapterOptions, public app: Application) {
    super(options)
  }
}
