// Generated by feathers-baas. Safe to edit.
import { authenticate } from '@feathersjs/authentication'
import { BadRequest, Forbidden } from '@feathersjs/errors'
import { iff, isProvider } from 'feathers-hooks-common'
import * as argon2 from 'argon2'
import type { HookContext } from '@feathersjs/feathers'
import type { Application } from '../../declarations.js'
import { checkPermissions } from '../../hooks/permission-check.js'

// ─── Password hashing ────────────────────────────────────────────────────────

async function hashPassword(context: HookContext<Application>): Promise<void> {
  const data = context.data as Record<string, unknown> | undefined
  if (!data || typeof data['password'] !== 'string') return

  const config = context.app.get('config')
  data['password'] = await argon2.hash(data['password'] as string, {
    type: argon2.argon2id,
    memoryCost: config.argon2.memoryCost,
    timeCost: config.argon2.timeCost,
    parallelism: config.argon2.parallelism,
  })
}

// ─── Strip password on output ────────────────────────────────────────────────

function stripPassword(context: HookContext<Application>): void {
  const strip = (user: unknown): unknown => {
    if (user && typeof user === 'object') {
      const u = user as Record<string, unknown>
      delete u['password']
    }
    return user
  }

  if (Array.isArray(context.result)) {
    context.result = context.result.map(strip)
  } else if (context.result && typeof context.result === 'object') {
    const result = context.result as { data?: unknown[]; total?: number }
    if (Array.isArray(result.data)) {
      result.data = result.data.map(strip)
    } else {
      strip(context.result)
    }
  }
}

// ─── Role guards ─────────────────────────────────────────────────────────────

function setDefaultRole(context: HookContext<Application>): void {
  const data = context.data as Record<string, unknown>
  if (!data['roles'] || (Array.isArray(data['roles']) && (data['roles'] as unknown[]).length === 0)) {
    data['roles'] = ['user']
  }
}

function preventAdminRole(context: HookContext<Application>): void {
  const data = context.data as Record<string, unknown>
  const roles = data['roles'] as string[] | undefined
  if (roles?.includes('admin')) {
    throw new Forbidden('Cannot self-assign the admin role via REST')
  }
}

function preventEmptyRoles(context: HookContext<Application>): void {
  const data = context.data as Record<string, unknown>
  if (Array.isArray(data['roles']) && (data['roles'] as unknown[]).length === 0) {
    throw new BadRequest('roles cannot be an empty array')
  }
}

// ─── Uniqueness check ────────────────────────────────────────────────────────

async function checkEmailUnique(context: HookContext<Application>): Promise<void> {
  const data = context.data as Record<string, unknown>
  if (!data['email']) return

  // Use _find (internal, bypasses hooks) to check for existing email
  const svc = context.service as unknown as {
    _find(p: object): Promise<{ total: number }>
  }
  const existing = await svc._find({
    query: { email: data['email'], $limit: 1 },
    paginate: { default: 1, max: 1 },
  })

  if (existing.total > 0) {
    throw new BadRequest('An account with this email already exists')
  }
}

// ─── Soft-delete filter ───────────────────────────────────────────────────────

function filterDeleted(context: HookContext<Application>): void {
  context.params.query = {
    ...context.params.query,
    deletedAt: null,
  }
}

// ─── Hook chains ─────────────────────────────────────────────────────────────

export const usersHooks = {
  around: {
    all: [],
    find: [authenticate('jwt')],
    get: [authenticate('jwt')],
    create: [],
    update: [authenticate('jwt')],
    patch: [authenticate('jwt')],
    remove: [authenticate('jwt')],
  },
  before: {
    all: [],
    find: [
      iff(isProvider('rest'), checkPermissions),
      filterDeleted,
    ],
    get: [iff(isProvider('rest'), checkPermissions)],
    create: [
      setDefaultRole,
      iff(isProvider('rest'), preventAdminRole),
      checkEmailUnique,
      hashPassword,
    ],
    update: [iff(isProvider('rest'), checkPermissions)],
    patch: [
      iff(isProvider('rest'), checkPermissions),
      iff(isProvider('rest'), preventAdminRole),
      preventEmptyRoles,
      hashPassword,
    ],
    remove: [iff(isProvider('rest'), checkPermissions)],
  },
  after: {
    all: [stripPassword],
    create: [],
  },
  error: {},
}
