// Generated by feathers-baas. Safe to edit.
import type { Application } from '../../declarations.js'
import { UsersClass } from './users.class.js'
import { usersHooks } from './users.hooks.js'

export type { UsersClass as UsersService }

export function configureUsers(app: Application): void {
  const knex = app.get('knex')

  app.use('users', new UsersClass({ Model: knex, name: 'users', paginate: { default: 10, max: 100 } }, app), {
    methods: ['find', 'get', 'create', 'patch', 'remove'],
    events: [],
  })

  app.service('users').hooks(usersHooks)
}
