// Generated by feathers-baas. Safe to edit.
import { TransactionalEmailsApi, TransactionalEmailsApiApiKeys, SendSmtpEmail } from '@getbrevo/brevo'
import * as ejs from 'ejs'
import type { NotifierDriver, Notification } from '../types.js'

// ejs is a CommonJS module — alias the render function defensively
const ejsRender = (ejs as unknown as { render?: typeof ejs.render }).render ?? ejs.render

export interface BrevoDriverOptions {
  /** Brevo API key (from https://app.brevo.com/settings/keys/api). */
  apiKey: string
  /** Display name shown in the From field. */
  fromName: string
  /** Verified sender address. Must be verified in your Brevo account. */
  fromAddress: string
}

/**
 * Email driver backed by the Brevo (formerly Sendinblue) Transactional Email API.
 * Templates are rendered with EJS at send time.
 */
export class BrevoDriver implements NotifierDriver {
  readonly name = 'brevo'

  private readonly apiInstance: TransactionalEmailsApi

  constructor(private readonly opts: BrevoDriverOptions) {
    this.apiInstance = new TransactionalEmailsApi()
    this.apiInstance.setApiKey(TransactionalEmailsApiApiKeys.apiKey, opts.apiKey)
  }

  async send(notification: Notification): Promise<void> {
    const html = ejsRender(notification.bodyTemplate, notification.data, { async: false })
    const text = notification.textTemplate
      ? ejsRender(notification.textTemplate, notification.data, { async: false })
      : undefined

    const email = new SendSmtpEmail()
    email.sender = { name: this.opts.fromName, email: this.opts.fromAddress }
    email.to = [{ email: notification.to }]
    email.subject = notification.subject ?? '(no subject)'
    email.htmlContent = html
    if (text) email.textContent = text

    await this.apiInstance.sendTransacEmail(email)
  }
}
