// Generated by feathers-baas. Safe to edit.
import { Resend } from 'resend'
import * as ejs from 'ejs'
import type { NotifierDriver, Notification } from '../types.js'

const ejsRender = (ejs as unknown as { render?: typeof ejs.render }).render ?? ejs.render

export interface ResendDriverOptions {
  /** Resend API key (from https://resend.com/api-keys). */
  apiKey: string
  /** Display name shown in the From field. */
  fromName: string
  /** Verified sender address. Must be a verified domain in your Resend account. */
  fromAddress: string
}

/**
 * Email driver backed by the Resend transactional email API.
 * Templates are rendered with EJS at send time.
 *
 * Resend offers generous free tier and excellent deliverability,
 * making it the recommended choice for new projects.
 */
export class ResendDriver implements NotifierDriver {
  readonly name = 'resend'

  private readonly client: Resend

  constructor(private readonly opts: ResendDriverOptions) {
    this.client = new Resend(opts.apiKey)
  }

  async send(notification: Notification): Promise<void> {
    const html = ejsRender(notification.bodyTemplate, notification.data, { async: false })
    const text = notification.textTemplate
      ? ejsRender(notification.textTemplate, notification.data, { async: false })
      : undefined

    const result = await this.client.emails.send({
      from: `${this.opts.fromName} <${this.opts.fromAddress}>`,
      to: [notification.to],
      subject: notification.subject ?? '(no subject)',
      html,
      text,
    })

    if ('error' in result && result.error) {
      throw new Error(`Resend error: ${result.error.message}`)
    }
  }
}
