// Generated by feathers-baas. Safe to edit.
import sgMail from '@sendgrid/mail'
import * as ejs from 'ejs'
import type { NotifierDriver, Notification } from '../types.js'

// ejs is a CommonJS module — alias the render function defensively
const ejsRender = (ejs as unknown as { render?: typeof ejs.render }).render ?? ejs.render

export interface SendGridDriverOptions {
  /** SendGrid API key (from https://app.sendgrid.com/settings/api_keys). */
  apiKey: string
  /** Display name shown in the From field. */
  fromName: string
  /** Verified sender address. Must be verified in your SendGrid account. */
  fromAddress: string
}

/**
 * Email driver backed by the SendGrid API.
 * Templates are rendered with EJS at send time.
 */
export class SendGridDriver implements NotifierDriver {
  readonly name = 'sendgrid'

  constructor(private readonly opts: SendGridDriverOptions) {
    sgMail.setApiKey(opts.apiKey)
  }

  async send(notification: Notification): Promise<void> {
    const html = ejsRender(notification.bodyTemplate, notification.data, { async: false })
    const text = notification.textTemplate
      ? ejsRender(notification.textTemplate, notification.data, { async: false })
      : undefined

    await sgMail.send({
      from: { name: this.opts.fromName, email: this.opts.fromAddress },
      to: notification.to,
      subject: notification.subject ?? '(no subject)',
      html,
      ...(text ? { text } : {}),
    })
  }
}
