// Generated by feathers-baas. Safe to edit.
import nodemailer from 'nodemailer'
import * as ejs from 'ejs'
import type { NotifierDriver, Notification } from '../types.js'

// ejs is a CommonJS module — alias the render function defensively
const ejsRender = (ejs as unknown as { render?: typeof ejs.render }).render ?? ejs.render

export interface SMTPDriverOptions {
  /** SMTP connection URL, e.g. smtp://user:pass@mail.example.com:587 */
  url: string
  /** Display name shown in the From field. */
  fromName: string
  /** Email address shown in the From field. */
  fromAddress: string
}

/**
 * Email driver backed by nodemailer over SMTP.
 * Templates are rendered with EJS at send time.
 *
 * Use this driver for self-hosted SMTP servers (Postfix, Mailtrap, etc.).
 * For transactional email services, prefer ResendDriver.
 */
export class SMTPDriver implements NotifierDriver {
  readonly name = 'smtp'

  private readonly transporter: nodemailer.Transporter

  constructor(private readonly opts: SMTPDriverOptions) {
    this.transporter = nodemailer.createTransport(opts.url)
  }

  async send(notification: Notification): Promise<void> {
    const html = ejsRender(notification.bodyTemplate, notification.data, { async: false })
    const text = notification.textTemplate
      ? ejsRender(notification.textTemplate, notification.data, { async: false })
      : undefined

    await this.transporter.sendMail({
      from: `"${this.opts.fromName}" <${this.opts.fromAddress}>`,
      to: notification.to,
      subject: notification.subject ?? '(no subject)',
      html,
      text,
    })
  }

  /** Verify SMTP connectivity. Throws if the server is unreachable. */
  async verify(): Promise<void> {
    await this.transporter.verify()
  }

  /** Close the underlying connection pool. */
  close(): void {
    this.transporter.close()
  }
}
