// Generated by feathers-baas. Safe to edit.
import { Cli, Builtins } from 'clipanion'
import { InitCommand } from './commands/init.js'
import { GenerateServiceCommand } from './commands/generate-service.js'
import { GenerateHookCommand } from './commands/generate-hook.js'
import { DoctorCommand } from './commands/doctor.js'
import { DescribeCommand } from './commands/describe.js'
import { SeedCommand } from './commands/seed.js'

const cli = new Cli({
  binaryLabel: 'feathers-baas',
  binaryName: 'feathers-baas',
  binaryVersion: '0.0.1',
})

cli.register(InitCommand)
cli.register(GenerateServiceCommand)
cli.register(GenerateHookCommand)
cli.register(DoctorCommand)
cli.register(DescribeCommand)
cli.register(SeedCommand)
cli.register(Builtins.HelpCommand)
cli.register(Builtins.VersionCommand)

cli.runExit(process.argv.slice(2))
