// Generated by feathers-baas. Safe to edit.
import { Cli, Builtins } from 'clipanion'
import { GenerateServiceCommand } from './commands/generate-service.js'
import { GenerateHookCommand } from './commands/generate-hook.js'

const cli = new Cli({
  binaryLabel: 'feathers-baas',
  binaryName: 'feathers-baas',
  binaryVersion: '0.0.1',
})

cli.register(GenerateServiceCommand)
cli.register(GenerateHookCommand)
cli.register(Builtins.HelpCommand)
cli.register(Builtins.VersionCommand)

cli.runExit(process.argv.slice(2))
