// Generated by feathers-baas. Safe to edit.
import { readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

export type Database = 'postgresql' | 'mysql' | 'sqlite' | 'mongodb'

export function detectDatabase(projectRoot: string): Database {
  const pkgPath = join(projectRoot, 'package.json')
  if (existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8')) as {
        dependencies?: Record<string, string>
      }
      const deps = pkg.dependencies ?? {}
      if (deps['mongodb']) return 'mongodb'
      if (deps['pg']) return 'postgresql'
      if (deps['mysql2']) return 'mysql'
      if (deps['better-sqlite3']) return 'sqlite'
    } catch {
      // fall through
    }
  }

  const envPath = join(projectRoot, '.env')
  if (existsSync(envPath)) {
    const env = readFileSync(envPath, 'utf-8')
    if (/^MONGODB_URL=/m.test(env)) return 'mongodb'
    if (/^MYSQL_URL=/m.test(env)) return 'mysql'
    if (/^SQLITE_FILENAME=/m.test(env)) return 'sqlite'
    if (/^DATABASE_URL=/m.test(env)) return 'postgresql'
  }

  return 'postgresql'
}
