// Generated by feathers-baas. Safe to edit.

/** "blog-posts" → "blogPosts" */
export function toCamelCase(s: string): string {
  return s.replace(/[-_]([a-z])/g, (_, c: string) => c.toUpperCase())
}

/** "blog-posts" → "BlogPosts" */
export function toPascalCase(s: string): string {
  const camel = toCamelCase(s)
  return camel.charAt(0).toUpperCase() + camel.slice(1)
}

/** "blogPosts" → "blog_posts" */
export function toSnakeCase(s: string): string {
  return s
    .replace(/[-]/g, '_')
    .replace(/([A-Z])/g, (c) => `_${c.toLowerCase()}`)
    .replace(/^_/, '')
}

/** "blog-posts" → "blog-posts" (kebab, already the default input format) */
export function toKebabCase(s: string): string {
  return s
    .replace(/([A-Z])/g, (c) => `-${c.toLowerCase()}`)
    .replace(/_/g, '-')
    .replace(/^-/, '')
}
