// Generated by feathers-baas. Safe to edit.
import chalk from 'chalk'

export function success(msg: string): void {
  console.log(chalk.green('✔'), msg)
}

export function info(msg: string): void {
  console.log(chalk.blue('ℹ'), msg)
}

export function warn(msg: string): void {
  console.log(chalk.yellow('⚠'), msg)
}

export function error(msg: string): void {
  console.error(chalk.red('✖'), msg)
}

export function fileCreated(filePath: string): void {
  console.log(chalk.green('  CREATE'), filePath)
}

export function filePatched(filePath: string): void {
  console.log(chalk.cyan('  PATCH '), filePath)
}
