// Generated by feathers-baas. Safe to edit.
import ejs from 'ejs'
import { readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
// In dist/: __dirname is packages/cli/dist — templates are at packages/cli/templates
// In src/: __dirname is packages/cli/src/utils — templates are at packages/cli/templates
const TEMPLATE_DIR = join(__dirname, '..', 'templates')

export function renderTemplate(
  templatePath: string,
  data: Record<string, unknown>,
): string {
  const fullPath = join(TEMPLATE_DIR, templatePath)
  const template = readFileSync(fullPath, 'utf-8')
  return ejs.render(template, data)
}
