// Generated by feathers-baas. Safe to edit.
import { KnexService } from '@feathersjs/knex'
import type { KnexAdapterParams, KnexAdapterOptions } from '@feathersjs/knex'
import { MongoDBService } from '@feathersjs/mongodb'
import type { MongoDBAdapterParams, MongoDBAdapterOptions } from '@feathersjs/mongodb'
import type { Application } from '../../declarations.js'
import type { Role, RoleData, RolePatch, RoleQuery } from './roles.schema.js'

export type RolesParams = KnexAdapterParams<RoleQuery>

export function parseRolePermissions(role: unknown): Role {
  const r = role as Role & { permissions: unknown }
  return {
    ...r,
    permissions:
      typeof r.permissions === 'string'
        ? (JSON.parse(r.permissions) as Role['permissions'])
        : r.permissions,
  }
}

// jsonb columns need a JSON string, not a JS array — node-postgres otherwise
// coerces arrays to a Postgres array literal and the insert fails with
// "invalid input syntax for type json". Applies to both internal (_create /
// _patch used by seedDatabase) and external callers.
function stringifyPermissions<T extends { permissions?: unknown }>(data: T): T {
  if (data.permissions === undefined || typeof data.permissions === 'string') return data
  return { ...data, permissions: JSON.stringify(data.permissions) as unknown as T['permissions'] }
}

export class RolesClass extends KnexService<Role, RoleData, RolesParams, RolePatch> {
  constructor(options: KnexAdapterOptions, public app: Application) {
    super(options)
  }

  override async _create(data: RoleData, params?: RolesParams): Promise<Role>
  override async _create(data: RoleData[], params?: RolesParams): Promise<Role[]>
  override async _create(data: RoleData | RoleData[], params?: RolesParams): Promise<Role | Role[]> {
    const normalized = Array.isArray(data) ? data.map(stringifyPermissions) : stringifyPermissions(data)
    return super._create(normalized as RoleData | RoleData[], params)
  }

  override async _patch(id: null, data: RolePatch, params?: RolesParams): Promise<Role[]>
  override async _patch(id: string, data: RolePatch, params?: RolesParams): Promise<Role>
  override async _patch(id: string | null, data: RolePatch, params?: RolesParams): Promise<Role | Role[]> {
    return super._patch(id as string, stringifyPermissions(data), params)
  }
}

export type RolesMongoParams = MongoDBAdapterParams<RoleQuery>

export class RolesMongoClass extends MongoDBService<Role, RoleData, RolesMongoParams, RolePatch> {
  constructor(options: MongoDBAdapterOptions, public app: Application) {
    super(options)
  }
}
