// Generated by feathers-baas. Safe to edit.
import { authenticate } from '@feathersjs/authentication'
import { iff, isProvider } from 'feathers-hooks-common'
import type { HookContext } from '@feathersjs/feathers'
import type { Application } from '../../declarations.js'
import { checkPermissions, invalidateRoleCache } from '../../hooks/permission-check.js'
import { setTimestamps } from '../../hooks/timestamps.js'
import { parseRolePermissions } from './roles.class.js'
import type { Role } from './roles.schema.js'

// Parse permissions JSONB string from Postgres on all read operations
function parsePermissions(context: HookContext<Application>): void {
  if (!context.result) return
  const parse = parseRolePermissions

  if (Array.isArray(context.result)) {
    context.result = context.result.map(parse)
  } else if (context.result && typeof context.result === 'object') {
    const result = context.result as { data?: unknown[]; total?: number }
    if (Array.isArray(result.data)) {
      result.data = result.data.map(parse)
    } else {
      context.result = parse(context.result)
    }
  }
}

// Invalidate the permission LRU cache whenever a role is mutated
function invalidateCache(context: HookContext<Application>): void {
  const result = context.result as Role | undefined
  invalidateRoleCache(result?.name)
}

export const rolesHooks = {
  around: {
    all: [authenticate('jwt')],
  },
  before: {
    all: [iff(isProvider('rest'), checkPermissions)],
    create: [setTimestamps],
    patch: [setTimestamps],
    remove: [],
  },
  after: {
    all: [parsePermissions],
    create: [invalidateCache],
    patch: [invalidateCache],
    remove: [invalidateCache],
  },
  error: {},
}
