// Generated by feathers-baas. Safe to edit.
import type { Application } from '../../declarations.js'
import { RolesClass } from './roles.class.js'
import { rolesHooks } from './roles.hooks.js'

export type { RolesClass as RolesService }

export function configureRoles(app: Application): void {
  const knex = app.get('knex')

  app.use(
    'roles',
    new RolesClass(
      { Model: knex, name: 'roles', paginate: { default: 50, max: 200 } },
      app,
    ),
    {
      methods: ['find', 'get', 'create', 'patch', 'remove'],
      events: [],
    },
  )

  app.service('roles').hooks(rolesHooks)
}
