// Generated by feathers-baas. Safe to edit.
import { KnexService } from '@feathersjs/knex'
import type { KnexAdapterParams, KnexAdapterOptions } from '@feathersjs/knex'
import type { Application } from '../../declarations.js'
import type { Role, RoleData, RolePatch, RoleQuery } from './roles.schema.js'

export type RolesParams = KnexAdapterParams<RoleQuery>

// Parse permissions JSONB from Postgres string back to objects.
// Applied via after hooks rather than overriding _find (avoids overload complexity).
export function parseRolePermissions(role: unknown): Role {
  const r = role as Role & { permissions: unknown }
  return {
    ...r,
    permissions:
      typeof r.permissions === 'string'
        ? (JSON.parse(r.permissions) as Role['permissions'])
        : r.permissions,
  }
}

export class RolesClass extends KnexService<Role, RoleData, RolesParams, RolePatch> {
  constructor(options: KnexAdapterOptions, public app: Application) {
    super(options)
  }
}
