// Generated by feathers-baas. Safe to edit.
import { Type, type Static, querySyntax } from '@feathersjs/typebox'

// A permission grants access to one or more methods on a named service.
export const permissionSchema = Type.Object(
  {
    service: Type.String(),
    methods: Type.Array(
      Type.Union([
        Type.Literal('*'),
        Type.Literal('find'),
        Type.Literal('get'),
        Type.Literal('create'),
        Type.Literal('update'),
        Type.Literal('patch'),
        Type.Literal('remove'),
      ]),
    ),
  },
  { $id: 'Permission', additionalProperties: false },
)

export type Permission = Static<typeof permissionSchema>

// Full DB row
export const roleSchema = Type.Object(
  {
    id: Type.String({ format: 'uuid' }),
    name: Type.String(),
    permissions: Type.Array(permissionSchema),
    createdAt: Type.String({ format: 'date-time' }),
    updatedAt: Type.String({ format: 'date-time' }),
  },
  { $id: 'Role', additionalProperties: false },
)

export type Role = Static<typeof roleSchema>

// Input for create
export const roleDataSchema = Type.Object(
  {
    name: Type.String({ minLength: 1 }),
    permissions: Type.Optional(Type.Array(permissionSchema)),
  },
  { $id: 'RoleData', additionalProperties: false },
)

export type RoleData = Static<typeof roleDataSchema>

// Input for patch
export const rolePatchSchema = Type.Partial(
  Type.Object({
    name: Type.String({ minLength: 1 }),
    permissions: Type.Array(permissionSchema),
  }),
  { $id: 'RolePatch', additionalProperties: false },
)

export type RolePatch = Static<typeof rolePatchSchema>

// Query parameters — querySyntax adds $limit, $skip, $sort, $select, $and, $or
export const roleQuerySchema = querySyntax(
  Type.Object({
    id: Type.Optional(Type.String()),
    name: Type.Optional(Type.String()),
  }),
  {},
  { $id: 'RoleQuery', additionalProperties: false },
)

export type RoleQuery = Static<typeof roleQuerySchema>
