// Generated by feathers-baas. Safe to edit.
import type { HookContext, NextFunction } from '@feathersjs/feathers'
import { logger } from '../logger.js'
import type { Application } from '../declarations.js'

export async function logError(
  context: HookContext<Application>,
  next: NextFunction,
): Promise<void> {
  try {
    await next()
  } catch (error: unknown) {
    logger.error(
      {
        err: error,
        service: context.path,
        method: context.method,
        provider: context.params.provider,
      },
      'Service error',
    )
    throw error
  }
}
