// Generated by feathers-baas. Safe to edit.
import { Forbidden } from '@feathersjs/errors'
import type { HookContext } from '@feathersjs/feathers'
import { LRUCache } from 'lru-cache'
import type { Application } from '../declarations.js'
import type { Role } from '../services/roles/roles.schema.js'

type PermissionMethod = '*' | 'find' | 'get' | 'create' | 'update' | 'patch' | 'remove'

// Cache role documents keyed by role name — TTL 5 minutes
const roleCache = new LRUCache<string, Role>({
  max: 500,
  ttl: 1000 * 60 * 5,
})

export function invalidateRoleCache(roleName?: string): void {
  if (roleName) {
    roleCache.delete(roleName)
  } else {
    roleCache.clear()
  }
}

async function resolveRoles(roleNames: string[], app: Application): Promise<Role[]> {
  const missing = roleNames.filter((n) => !roleCache.has(n))

  if (missing.length > 0) {
    // Internal call (no params.provider) — bypasses auth and permission hooks
    const result = await (app.service('roles') as { find(p: object): Promise<Role[] | { data: Role[] }> }).find({
      paginate: false,
      query: { name: { $in: missing } },
    })

    const rows: Role[] = Array.isArray(result) ? result : result.data
    for (const role of rows) {
      roleCache.set(role.name, role)
    }
  }

  return roleNames.flatMap((n) => {
    const r = roleCache.get(n)
    return r ? [r] : []
  })
}

export async function checkPermissions(context: HookContext<Application>): Promise<void> {
  const user = context.params.user as { roles?: string[] } | undefined

  if (!user) {
    throw new Forbidden('No authenticated user')
  }

  const userRoles: string[] = user.roles ?? []

  if (userRoles.length === 0) {
    throw new Forbidden('User has no roles assigned')
  }

  const roles = await resolveRoles(userRoles, context.app)
  const method = context.method as PermissionMethod

  const allowed = roles.some((role) =>
    role.permissions.some(
      (p) =>
        p.service === context.path &&
        (p.methods.includes('*') || p.methods.includes(method)),
    ),
  )

  if (!allowed) {
    throw new Forbidden(`Role does not permit ${method} on ${context.path}`)
  }
}
