// Generated by feathers-baas. Safe to edit.
import { LocalStrategy } from '@feathersjs/authentication-local'
import * as argon2 from 'argon2'

export class ArgonLocalStrategy extends LocalStrategy {
  override async comparePassword(user: Record<string, unknown>, password: string): Promise<boolean> {
    const hash = user['password'] as string | undefined
    if (!hash) return false
    return argon2.verify(hash, password)
  }
}
