// Generated by feathers-baas. Safe to edit.
import { Queue } from 'bullmq'
import type { Redis } from 'ioredis'
import type { NotificationJob } from '../types.js'

export const NOTIFICATION_QUEUE_NAME = 'feathers-baas:notifications'

/**
 * Create a BullMQ Queue instance for notification jobs.
 *
 * @example
 * ```ts
 * const redis = new Redis(process.env.REDIS_URL)
 * const queue = createNotificationQueue(redis)
 * await enqueueNotification(queue, { driverName: 'smtp', notification: { ... } })
 * ```
 */
export function createNotificationQueue(redis: Redis): Queue<NotificationJob> {
  return new Queue<NotificationJob>(NOTIFICATION_QUEUE_NAME, {
    connection: redis,
    defaultJobOptions: {
      attempts: 5,
      backoff: {
        type: 'exponential',
        delay: 1_000, // initial delay: 1s → 2s → 4s → 8s → 16s
      },
      removeOnComplete: { count: 100 },
      removeOnFail: { count: 500 },
    },
  })
}

/**
 * Enqueue a notification job.
 *
 * @param queue  BullMQ Queue instance from createNotificationQueue()
 * @param job    Job payload { driverName, notification }
 */
export async function enqueueNotification(
  queue: Queue<NotificationJob>,
  job: NotificationJob,
): Promise<void> {
  await queue.add('send', job)
}
