// Generated by feathers-baas. Safe to edit.
import { Worker } from 'bullmq'
import type { Redis } from 'ioredis'
import type { DriverRegistry } from '../registry.js'
import type { NotificationJob } from '../types.js'
import { NOTIFICATION_QUEUE_NAME } from './producer.js'

export interface WorkerOptions {
  /** BullMQ concurrency — number of jobs processed in parallel. */
  concurrency?: number
}

/**
 * Create and start the BullMQ worker that processes notification jobs.
 *
 * The worker looks up the driver from the registry by name, renders the
 * EJS template, and calls driver.send(). BullMQ handles retries with
 * exponential back-off automatically.
 *
 * Call worker.close() during graceful shutdown to drain in-flight jobs.
 *
 * @example
 * ```ts
 * const worker = createNotificationWorker(registry, redis, { concurrency: 5 })
 *
 * process.on('SIGTERM', async () => {
 *   await worker.close()
 * })
 * ```
 */
export function createNotificationWorker(
  registry: DriverRegistry,
  redis: Redis,
  opts: WorkerOptions = {},
): Worker<NotificationJob> {
  const concurrency = opts.concurrency ?? 5

  const worker = new Worker<NotificationJob>(
    NOTIFICATION_QUEUE_NAME,
    async (job) => {
      const { driverName, notification } = job.data

      const driver = registry.getDriver(driverName)
      if (!driver) {
        throw new Error(`Notification driver "${driverName}" is not registered`)
      }

      await driver.send(notification)
    },
    {
      connection: redis,
      concurrency,
      // Don't create a new redis connection per job — reuse the pool
      autorun: true,
    },
  )

  worker.on('failed', (job, err) => {
    // BullMQ handles retries; this is just for observability
    const jobId = job?.id ?? 'unknown'
    const message = err instanceof Error ? err.message : String(err)
    console.error(`[notifications] Job ${jobId} failed: ${message}`)
  })

  return worker
}
