// Generated by feathers-baas. Safe to edit.
import knexLib, { type Knex } from 'knex'
import type { Application } from '../declarations.js'
import { logger } from '../logger.js'

// Convert camelCase identifiers (column/table names in queries) to snake_case
// so JS camelCase field names map to snake_case DB columns transparently.
const toSnakeCase = (s: string): string => s.replace(/([A-Z])/g, (c) => `_${c.toLowerCase()}`)

// Convert snake_case column names in DB results back to camelCase.
// Only top-level row keys are converted — JSONB field contents are left as-is.
const toCamelCase = (s: string): string => s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())

function camelizeRow(obj: Record<string, unknown>): Record<string, unknown> {
  return Object.fromEntries(Object.entries(obj).map(([k, v]) => [toCamelCase(k), v]))
}

let _client: Knex | undefined

export function createKnexClient(databaseUrl: string): Knex {
  if (_client) return _client

  _client = knexLib({
    client: 'pg',
    connection: databaseUrl,
    pool: { min: 2, max: 10 },
    acquireConnectionTimeout: 10_000,
    wrapIdentifier: (value, origImpl) => origImpl(toSnakeCase(value)),
    postProcessResponse: (result) => {
      if (Array.isArray(result)) {
        return result.map((row) =>
          row !== null && typeof row === 'object' ? camelizeRow(row as Record<string, unknown>) : row,
        )
      }
      if (result !== null && typeof result === 'object') {
        return camelizeRow(result as Record<string, unknown>)
      }
      return result
    },
  })

  return _client
}

export async function configureKnex(app: Application): Promise<void> {
  const config = app.get('config')
  const knex = createKnexClient(config.postgres.url)

  // Fail fast — surface DB connection errors at startup
  try {
    await knex.raw('SELECT 1')
    logger.info('Database connected')
  } catch (err) {
    logger.error({ err }, 'Database connection failed')
    throw err
  }

  app.set('knex', knex)
}

export function getKnexClient(): Knex {
  if (!_client) throw new Error('Knex client not initialised — call configureKnex first')
  return _client
}
