// Generated by feathers-baas. Safe to edit.
import knexLib, { type Knex } from 'knex'
import type { Application } from '../declarations.js'
import { logger } from '../logger.js'

let _client: Knex | undefined

export function createKnexClient(databaseUrl: string): Knex {
  if (_client) return _client

  _client = knexLib({
    client: 'pg',
    connection: databaseUrl,
    pool: { min: 2, max: 10 },
    acquireConnectionTimeout: 10_000,
  })

  return _client
}

export async function configureKnex(app: Application): Promise<void> {
  const config = app.get('config')
  const knex = createKnexClient(config.postgres.url)

  // Fail fast — surface DB connection errors at startup
  try {
    await knex.raw('SELECT 1')
    logger.info('Database connected')
  } catch (err) {
    logger.error({ err }, 'Database connection failed')
    throw err
  }

  app.set('knex', knex)
}

export function getKnexClient(): Knex {
  if (!_client) throw new Error('Knex client not initialised — call configureKnex first')
  return _client
}
