// Generated by feathers-baas. Safe to edit.
import { MongoClient, type Db } from 'mongodb'
import type { Application } from '../declarations.js'
import { logger } from '../logger.js'

let _client: MongoClient | undefined
let _db: Db | undefined

export function createMongoClient(url: string, dbName?: string): { client: MongoClient; db: Db } {
  if (_client && _db) return { client: _client, db: _db }

  _client = new MongoClient(url)
  _db = _client.db(dbName)

  return { client: _client, db: _db }
}

export async function configureMongo(app: Application): Promise<void> {
  const config = app.get('config')
  if (!config.mongodb?.url) throw new Error('MongoDB not configured — set MONGODB_URL')
  const { client, db } = createMongoClient(config.mongodb.url, config.mongodb.dbName)

  try {
    await client.connect()
    await db.command({ ping: 1 })
    logger.info('MongoDB connected')
  } catch (err) {
    logger.error({ err }, 'MongoDB connection failed')
    throw err
  }

  app.set('mongoClient', client)
  app.set('mongoDb', db)
}

export function getMongoClient(): MongoClient {
  if (!_client) throw new Error('MongoDB client not initialised — call configureMongo first')
  return _client
}

export function getMongoDb(): Db {
  if (!_db) throw new Error('MongoDB not initialised — call configureMongo first')
  return _db
}
