// Generated by feathers-baas. Safe to edit.
import knexLib, { type Knex } from 'knex'
import type { Application } from '../declarations.js'
import { logger } from '../logger.js'

const toSnakeCase = (s: string): string => s.replace(/([A-Z])/g, (c) => `_${c.toLowerCase()}`)

const toCamelCase = (s: string): string => s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())

function camelizeRow(obj: Record<string, unknown>): Record<string, unknown> {
  return Object.fromEntries(Object.entries(obj).map(([k, v]) => [toCamelCase(k), v]))
}

let _client: Knex | undefined

export function createMysqlClient(connectionUrl: string): Knex {
  if (_client) return _client

  _client = knexLib({
    client: 'mysql2',
    connection: connectionUrl,
    pool: { min: 2, max: 10 },
    acquireConnectionTimeout: 10_000,
    wrapIdentifier: (value, origImpl) => origImpl(toSnakeCase(value)),
    postProcessResponse: (result) => {
      if (Array.isArray(result)) {
        return result.map((row) =>
          row !== null && typeof row === 'object' ? camelizeRow(row as Record<string, unknown>) : row,
        )
      }
      if (result !== null && typeof result === 'object') {
        return camelizeRow(result as Record<string, unknown>)
      }
      return result
    },
  })

  return _client
}

export async function configureMysql(app: Application): Promise<void> {
  const config = app.get('config')
  if (!config.mysql?.url) throw new Error('MySQL not configured — set MYSQL_URL')
  const knex = createMysqlClient(config.mysql.url)

  try {
    await knex.raw('SELECT 1')
    logger.info('MySQL connected')
  } catch (err) {
    logger.error({ err }, 'MySQL connection failed')
    throw err
  }

  app.set('knex', knex)
}

export function getMysqlClient(): Knex {
  if (!_client) throw new Error('MySQL client not initialised — call configureMysql first')
  return _client
}
