// Generated by feathers-baas. Safe to edit.
import knexLib, { type Knex } from 'knex'
import type { Application } from '../declarations.js'
import { logger } from '../logger.js'

const toSnakeCase = (s: string): string => s.replace(/([A-Z])/g, (c) => `_${c.toLowerCase()}`)

const toCamelCase = (s: string): string => s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())

function camelizeRow(obj: Record<string, unknown>): Record<string, unknown> {
  return Object.fromEntries(Object.entries(obj).map(([k, v]) => [toCamelCase(k), v]))
}

let _client: Knex | undefined

export function createSqliteClient(filename: string): Knex {
  if (_client) return _client

  _client = knexLib({
    client: 'better-sqlite3',
    connection: { filename },
    useNullAsDefault: true,
    pool: { min: 1, max: 1 },
    wrapIdentifier: (value, origImpl) => origImpl(toSnakeCase(value)),
    postProcessResponse: (result) => {
      if (Array.isArray(result)) {
        return result.map((row) =>
          row !== null && typeof row === 'object' ? camelizeRow(row as Record<string, unknown>) : row,
        )
      }
      if (result !== null && typeof result === 'object') {
        return camelizeRow(result as Record<string, unknown>)
      }
      return result
    },
  })

  return _client
}

export async function configureSqlite(app: Application): Promise<void> {
  const config = app.get('config')
  if (!config.sqlite?.filename) throw new Error('SQLite not configured — set SQLITE_FILENAME')
  const knex = createSqliteClient(config.sqlite.filename)

  try {
    await knex.raw('SELECT 1')
    logger.info('SQLite connected')
  } catch (err) {
    logger.error({ err }, 'SQLite connection failed')
    throw err
  }

  app.set('knex', knex)
}

export function getSqliteClient(): Knex {
  if (!_client) throw new Error('SQLite client not initialised — call configureSqlite first')
  return _client
}
